# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless-ngx
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: ${CONTAINER_UID}
        runAsGroup: ${CONTAINER_GID}
        fsGroup: ${CONTAINER_FSGROUP}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      paperless:
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        containers:
          app:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.18.4
            envFrom:
              - secretRef:
                  name: paperless
            env:
              PAPERLESS_CONSUMER_POLLING: 60
              PAPERLESS_CONSUMER_RECURSIVE: 'true'
              PAPERLESS_CONSUMPTION_DIR: /library/consume
              PAPERLESS_DATA_DIR: /library/data
              PAPERLESS_EXPORT_DIR: /library/export
              PAPERLESS_MEDIA_ROOT: /library/media
              PAPERLESS_ENABLE_HTTP_REMOTE_USER: 'true'
              PAPERLESS_HTTP_REMOTE_USER_HEADER_NAME: HTTP_X_AUTHENTIK_USERNAME
              PAPERLESS_ADMIN_USER: tom
              PAPERLESS_OCR_LANGUAGE: eng
              PAPERLESS_PORT: 8080
              PAPERLESS_REDIS: redis://localhost:6379
              PAPERLESS_TASK_WORKERS: 2
              PAPERLESS_TIKA_ENABLED: 1
              PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://localhost:3000
              PAPERLESS_TIKA_ENDPOINT: http://localhost:9998
              PAPERLESS_TIME_ZONE: ${TZ}
              PAPERLESS_URL: https://documents.${S_HOMEPROD_DOMAIN}
              USERMAP_UID: ${CONTAINER_UID}
              USERMAP_GID: ${CONTAINER_GID}
              PAPERLESS_DBENGINE: postgresql
              PAPERLESS_DBPORT:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-paperless
                    key: port
              PAPERLESS_DBHOST:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-paperless
                    key: host
              PAPERLESS_DBNAME:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-paperless
                    key: dbname
              PAPERLESS_DBUSER:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-paperless
                    key: user
              PAPERLESS_DBPASS:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-paperless
                    key: password
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
          gotenburg:
            image:
              repository: thecodingmachine/gotenberg
              tag: 8.23.1
            env:
              DISABLE_GOOGLE_CHROME: 1
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
          redis:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.2.1
            probes:
              liveness:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
              readiness:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
              startup:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
                  failureThreshold: 30
                  periodSeconds: 5
          tika:
            image:
              repository: ghcr.io/paperless-ngx/tika
              tag: 2.9.1-full
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: paperless
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://documents.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host documents.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        enabled: true
        existingClaim: paperless-nfs
        globalMounts:
          - path: /library
