---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-operator
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: grafana-operator
      version: 5.24.0
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    # Use cluster-wide RBAC if we need cross-namespace CR watching
    rbac:
      create: true
      useClusterRole: true
