---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: multus
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: multus
      version: 5.0.7
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.1.3-thick
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.5.1
      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin
    hostPaths:
      netns: /var/run/netns
