---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: multus
  namespace: networking
spec:
  chartRef:
    kind: OCIRepository
    name: multus
  interval: 30m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    cni:
      netPath: /etc/cni/net.d
      binPath: /opt/cni/bin
