kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
    name: ghcr-secret
    namespace: default
data:
    .dockerconfigjson: ENC[AES256_GCM,data:WoIT3y5xEO/2+4mAEYr+wGssLDIgm8rnF5et2ZNQz2R8LgbKGOFFKtRsXX+CWujN+O7ugu78My3Cr+/Ir++M39ocvQLf7VDtjf3ydf6a+w9Qeyk0Q6DHbSara/J9twVi5pLnNs5QOIJCioOb+hZXQPtQI3ABVRinYwpfqY8vAx822HOYXzQRrcJ8omE=,iv:w7a/DFy9BQ3tmaZwLa++k237ArD6+ebHi1AoZ4mxIac=,tag:LcUxOp2FQuqrO/QSbN9NWg==,type:str]
sops:
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXRkL3FaMkgybVBLZ0lZ
            K2hFaG1rWGdpSHZmMmdjWmo1eVVOcDZPQ1c4Ck1iNGlxSkdLVG5FdVlwVGthRGVu
            REJBNWpVK1VXNDg3aTdvTjdjeWxTZ3cKLS0tIHNZeFNyNXYvNWE0TVdtWndEZytK
            OE90MWErSVdRdUVNT0U3WVNnVW5KMTQK0KbzxXlNtFtJGPavyfl9bpaeuSBA3DtJ
            N/AKD4ilUMNAr1h1X5+MYQl+A8b5ahp+u5mcF6s1IT8jCly8vj4JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-19T11:39:22Z"
    mac: ENC[AES256_GCM,data:TseskYI3DdkLceliA4gFncoSXJxfFPXGihBsDMfvz665bdGS6hnQD7yh4QRcaqNnKEYUG6WxcYi8Jg8BFu65I+Jo7k4c9zunq3x2EyHaRFUJOBjBhQ+SPDKnP0RVZTHj9kBWma6G8znHvENejvQxpYPJ72P/aYWrbzY2O7z4A2Q=,iv:k4EwpTK5qN1G/jrBQwIshImu6AO4ju0cr23giqLlKR0=,tag:RDR7agVfe5jt8gY4Xove8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
