# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: travel-tracker
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${CONTAINER_UID}
        runAsGroup: ${CONTAINER_GID}
        fsGroup: ${CONTAINER_FSGROUP}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: ghcr-secret
    controllers:
      "travel-tracker":
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        containers:
          app:
            image:
              repository: ghcr.io/tomcranitch/travel-tracker
              tag: latest  # TODO
            env:
              STADIA_API_KEY:
                valueFrom:
                  secretKeyRef:
                    name: travel-tracker
                    key: STADIA_API_KEY
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: "travel-tracker"
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host travel-tracker.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx