---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: immich-cluster
  namespace: default
  labels:
    crunchy-userinit.ramblurr.github.com/enabled: "true"
    crunchy-userinit.ramblurr.github.com/superuser: "postgres"
spec:
  postgresVersion: 16
  image: ghcr.io/budimanjojo/crunchy-postgres-vectorchord:ubi9-16.9-2520-0.4.3
  instances:
    - name: postgres
      replicas: 3
      dataVolumeClaimSpec:
        # TODO: move to local storage
        storageClassName: ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/data: postgres
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        parameters:
          shared_preload_libraries: "vchord.so"
          search_path: '"$user", public, vectors'
        pg_hba:
          - hostnossl all all 10.244.0.0/16 md5
  databaseInitSQL:
    name: immich-database-init-sql
    key: init.sql
  users:
    - name: postgres
      databases:
        - postgres
      password: 
        type: AlphaNumeric
    - name: immich
      databases:
        - immich
      password: 
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &brcfg
        - secret:
            name: crunchy-backup-secret
      repos:
        - name: repo1
          s3: &brrepos3
            bucket: homeprod-crunchy
            endpoint: https://s3.us-east-005.backblazeb2.com
            region: us-east-005
          schedules:
            full: "15 3 * * 2"
            differential: "15 4 * * *"
            incremental: "0 * * * *"
      global: &brgflags
        repo1-retention-diff: "10"
        repo1-retention-full: "120"
        repo1-retention-full-type: time
        archive-timeout: "180"
        repo1-path: /immich/
      manual:
        repoName: repo1
        options:
          - --type=full
  dataSource:
    pgbackrest:
      stanza: db
      configuration: *brcfg     
      global: *brgflags
      repo:
        name: repo1
        s3: *brrepos3
  
  # TODO: datasource
  # TODO: proxy.pgBouncer
