---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: default-cluster
  namespace: default
  labels:
    crunchy-userinit.ramblurr.github.com/enabled: "true"
    crunchy-userinit.ramblurr.github.com/superuser: "postgres"
spec:
  postgresVersion: 16
  instances:
    - name: postgres
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 35Gi
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: "kubernetes.io/hostname"
          whenUnsatisfiable: "DoNotSchedule"
          labelSelector:
            matchLabels:
              postgres-operator.crunchydata.com/data: postgres
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
  users:
    - name: postgres
      databases:
        - postgres
      password: 
        type: AlphaNumeric
    - name: authentik
      databases:
        - authentik
      password: 
        type: AlphaNumeric
    - name: linkding
      databases:
        - linkding
      password: 
        type: AlphaNumeric
    - name: mealie
      databases:
        - mealie
      password: 
        type: AlphaNumeric
    - name: paperless
      databases:
        - paperless
      password: 
        type: AlphaNumeric
    - name: vaultwarden
      databases:
        - vaultwarden
      password: 
        type: AlphaNumeric
    - name: windmill
      databases:
        - windmill
      password: 
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration: &brcfg
        - secret:
            name: crunchy-backup-secret
      repos:
        - name: repo1
          s3: &brrepos3
            bucket: homeprod-crunchy
            endpoint: https://s3.us-east-005.backblazeb2.com
            region: us-east-005
          schedules:
            full: "15 3 * * 2"
            differential: "15 4 * * *"
            incremental: "0 * * * *"
      global: &brgflags
        repo1-retention-diff: "21"
        repo1-retention-full: "120"
        repo1-retention-full-type: time
        repo1-path: /default/
        # TODO: repo1-bundle=y
      manual:
        repoName: repo1
        options:
          - --type=full
  dataSource:
    pgbackrest:
      stanza: db
      configuration: *brcfg     
      global: *brgflags
      repo:
        name: repo1
        s3: *brrepos3
  
  # TODO: datasource
  # TODO: proxy.pgBouncer
