---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich-database-init-sql
data:
  init.sql: |-
    \c immich\\
    BEGIN;
    ALTER DATABASE immich OWNER TO immich;
    CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
    CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;
    COMMIT;
