---
cluster:
  name: "homeprod"
  id: "1"

securityContext:
  privileged: true

kubeProxyReplacement: "strict"
# kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
k8sServiceHost: 192.168.29.157  # TODO
k8sServicePort: 6443

# ipv4NativeRoutingCIDR: 10.10.0.0/116

ipam:
  mode: "kubernetes"

containerRuntime:
  integration: containerd

hubble:
  enabled: false

ipv6:
  enabled: false

bgp:
 enabled: true
 announce:
   loadbalancerIP: true
