---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 15m
  chart:
    spec:
      chart: node-feature-discovery
      version: 0.17.1
      sourceRef:
        kind: HelmRepository
        name: node-feature-discovery-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    worker:
      config:
        core:
          sources: 
            - pci
            - system
            - usb
