---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2024.4.0
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      targetPath: authentik.secret_key
      valuesKey: secret_key
    - kind: Secret
      name: default-cluster-pguser-authentik
      targetPath: authentik.postgresql.name
      valuesKey: dbname
    - kind: Secret
      name: default-cluster-pguser-authentik
      targetPath: authentik.postgresql.user
      valuesKey: user
    - kind: Secret
      name: default-cluster-pguser-authentik
      targetPath: authentik.postgresql.password
      valuesKey: password
    - kind: Secret
      name: default-cluster-pguser-authentik
      targetPath: authentik.postgresql.host
      valuesKey: host
  values:
    authentik:
      email:
        from: tom@cranitch.com.au
    redis:
      enabled: true
    postgres:
      enabled: false
    server:
      initContainers:
        01-init-db:
          image:
            repository: ghcr.io/onedr0p/postgres-init
            tag: 14.8
          envFrom:
            - secretRef:
                name: authentik-secret
          env:
            - name: INIT_POSTGRES_HOST
              value: ${POSTGRES_RW_URL}
            - name: INIT_POSTGRES_SUPER_PASS
              valueFrom:
                secretKeyRef:
                  name: postgres-superuser
                  key: password
      ingress:
        enabled: true
        ingressClassName: nginx
        hosts:
          - &host "sso.${S_HOMEPROD_DOMAIN}"
        paths:
          - /
        tls:
          - hosts:
              - *host
    global:
      volumeMounts:
        - mountPath: /blueprints/custom
          name: authentik-blueprints
      volumes: 
        - configMap:
            name: authentik-blueprints
          name: authentik-blueprints
