---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: authentik
      version: 2023.10.2
      sourceRef:
        kind: HelmRepository
        name: authentik-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: authentik-secret
      targetPath: authentik.secret_key
      valuesKey: secret_key
    - kind: Secret
      name: authentik-secret
      targetPath: authentik.postgresql.name
      valuesKey: POSTGRES_DB
    - kind: Secret
      name: authentik-secret
      targetPath: authentik.postgresql.user
      valuesKey: POSTGRES_USER
    - kind: Secret
      name: authentik-secret
      targetPath: authentik.postgresql.password
      valuesKey: POSTGRES_PASS
  values:
    authentik:
      email:
        from: tom@cranitch.com.au
      postgresql:
        host: ${POSTGRES_RW_URL}
    redis:
      enabled: true
    postgres:
      enabled: false
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: &host "sso.${S_HOMEPROD_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - *host
    volumeMounts:
      - mountPath: /blueprints/custom
        name: authentik-blueprints
    volumes: 
      - configMap:
          name: authentik-blueprints
        name: authentik-blueprints
