---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - helmrelease.yaml
  - secret.sops.yaml
    # - ingress-outpost.yaml
patchesStrategicMerge:
  - patches/postgres.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - flow-authentication.yaml=./blueprints/flow-authentication.yaml
      - flow-authentication-ldap.yaml=./blueprints/flow-authentication-ldap.yaml
      - flow-invalidation.yaml=./blueprints/flow-invalidation.yaml
      - flow-topt-setup.yaml=./blueprints/flow-topt-setup.yaml
      - flow-webauthn-setup.yaml=./blueprints/flow-webauthn-setup.yaml
generatorOptions:
  disableNameSuffixHash: true
