---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: authentik-operator-charts
  namespace: flux-system
spec:
  interval: 1h
  url: https://slashnephy.github.io/authentik-operator
