---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: ocis-charts
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/owncloud/ocis-charts
  ref:
    # TODO configure renovate
    tag: v0.5.0
  ignore: |-
    # exclude all
    /*
    # include charts directory
    !/charts/ocis
