---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.14.3
      sourceRef:
        kind: HelmRepository
        name: victoriametrics-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      grafana.ini:
        server:
          root_url: "https://monitoring.${S_HOMEPROD_DOMAIN}"
        analytics:
          check_for_updates: false
        auth:
          oauth_auto_login: true
        auth.basic:
          disable_login_form: false
        auth.generic_oauth:
          enabled: true
          name: cranitchsso
          client_id: "${S_GRAFANA_OAUTH_CLIENT_ID}"
          client_secret: "${S_GRAFANA_OAUTH_CLIENT_SECRET}"
          scopes: "openid profile email"
          empty_scopes: false
          auth_url: https://${SSO_DOMAIN_PREFIX}.${S_BASE_DOMAIN}/application/o/authorize/
          token_url: https://${SSO_DOMAIN_PREFIX}.${S_BASE_DOMAIN}/application/o/token/
          api_url: https://${SSO_DOMAIN_PREFIX}.${S_BASE_DOMAIN}/application/o/userinfo/
          login_attribute_path: preferred_username
          groups_attribute_path: groups
          name_attribute_path: name
          allow_assign_grafana_admin: true
          # TODO more from Admin to GrafanaAdmin
          role_attribute_path: contains(groups[*], 'service-admins') && 'Admin' || 'Viewer'
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - &host "monitoring.${S_HOMEPROD_DOMAIN}"
        tls:
          - hosts:
            - *host
      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: "default"
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          # TODO flux dashboard
          proxmoxVM:
            gneId: 13307
            revision: 6
            datasource: VictoriaMetrics
          proxmox:
            gneId: 10048
            revision: 4
            datasource: VictoriaMetrics
    vmagent:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - "vmagent.${S_HOMEPROD_DOMAIN}"
        tls:
          - hosts:
            - "vmagent.${S_HOMEPROD_DOMAIN}"
    vmsingle:
      spec:
        storage:
          storageClassName: "ceph-block"
          resources:
            requests:
              storage: 30Gi
