---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 0.14.17
      sourceRef:
        kind: HelmRepository
        name: victoriametrics-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      enabled: false
    vmagent:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - &vmagent-host "vmagent.${HOMEPROD_DOMAIN}"
        tls:
          - hosts:
            - *vmagent-host
    vmsingle:
      spec:
        storage:
          storageClassName: "ceph-block"
          resources:
            requests:
              storage: 30Gi
# TODO: fix security errors (based on flux helm-controller logs)
#   victoria-metrics-operator:
#     securityContext:
#         runAsGroup: 1000
#         runAsUser: 1000
#         runAsNonRoot: true
#         allowPrivilegeEscalation: false
#         capabilities:
#           drop:
#             - ALL
#         seccompProfile.type: RuntimeDefault
            
