---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: victoria-metrics-k8s-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: victoria-metrics-k8s-stack
      version: 40.1.0
      sourceRef:
        kind: HelmRepository
        name: victoriametrics-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    grafana:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - "grafana.${S_HOMEPROD_DOMAIN}"
        tls:
          - "grafana.${S_HOMEPROD_DOMAIN}"
    vmcluster:
      ingress:
        enabled: true
        ingressClassName: "nginx"
        hosts:
          - "vmcluster.${S_HOMEPROD_DOMAIN}"
        tls:
          - "vmcluster.${S_HOMEPROD_DOMAIN}"
