---
apiVersion: v1
kind: Secret
metadata:
  name: victoria-metrics-restic
  namespace: monitoring
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${S_VOLSYNC_B2_REPO}-victoria-metrics
  RESTIC_PASSWORD: ${S_VOLSYNC_B2_PASSWORD}
  B2_ACCOUNT_ID: ${S_VOLSYNC_B2_ID}
  B2_ACCOUNT_KEY: ${S_VOLSYNC_B2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: victoria-metrics-restic
  namespace: monitoring
spec:
  sourcePVC: vmsingle-victoria-metrics-k8s-stack
  # trigger:
  #   schedule: "0 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: victoria-metrics-restic
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 111
      runAsGroup: 111
      fsGroup: 111
    retain:
      daily: 7
      within: 3d
