---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-driver-nfs
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: csi-driver-nfs
      version: v4.4.0
      sourceRef:
        kind: HelmRepository
        name: csi-driver-nfs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubeletDir: /var/lib/kubelet
