---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-slow
provisioner: nfs.csi.k8s.io
parameters:
  server: ${S_NFS_SERVER}
  share: /mnt/data/k8s
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.2
  - nconnect=8
  - hard
  - noatime
