---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: fluent-bit
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: fluent-bit
      version: fluent-bit-0.46.1
      sourceRef:
        kind: HelmRepository
        name: fluent-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    config:
      outputs: |
        [OUTPUT]
          Name stdout
          Match .*
