---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: ntfy
  namespace: flux-system
spec:
  type: generic
  address: https://windmill.staging.cranit.ch/api/w/default/capture_u/u/tom/shiny_flow
  secretRef:
    name: ntfy-flux-secret
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Alert
metadata:
  name: ntfy
  namespace: flux-system
spec:
  providerRef:
    name: ntfy
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: "*"
