---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: postgres
  namespace: database
  labels:
    crunchy-userinit.ramblurr.github.com/enabled: "true"
    crunchy-userinit.ramblurr.github.com/superuser: "postgres"
spec:
  postgresVersion: 16
  image: ghcr.io/chkpwd/cdpgvecto.rs:ubi8-16.2-0-v0.2.0
  instances:
    - name: postgres
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
        parameters:
          shared_preload_libraries: "vectors.so"
          search_path: '"$user", public, vectors'
  users:
    - name: postgres
      databases:
        - postgres
      options: "SUPERUSER"
      password: 
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: crunchy-backup-secret
      repos:
        - name: repo1
          s3:
            bucket: homeprod-crunchy
            endpoint: https://s3.us-east-005.backblazeb2.com
            region: us-east-005
          schedules:
            full: "0 3 * * 2"
            differential: "0 4 * * *"
            incremental: "0/15 * * * *"
      global:
        repo1-retention-differential: "21"
        repo1-retention-full: "120"
        repo1-retention-full-type: time
  # TODO: datasource
  # TODO: proxy.pgBouncer
