---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO: renovate
  - https://github.com/prometheus-operator/prometheus-operator/releases/download/v0.69.1/stripped-down-crds.yaml
