---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.14.5
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    cluster:
      name: "homeprod"
      id: "1"
    securityContext:
      privileged: true
    kubeProxyReplacement: "strict"
    # kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    k8sServiceHost: 192.168.29.172  # TODO
    k8sServicePort: 6443
    # ipv4NativeRoutingCIDR: 10.10.0.0/116
    ipam:
      mode: "kubernetes"
    containerRuntime:
      integration: containerd
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: "nginx"
          hosts:
            - &host hubble.${S_HOMEPROD_DOMAIN}
          tls:
            - hosts:
                - *host
    ipv6:
      enabled: false
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
    cni:
      exclusive: false
