---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.15.5
      sourceRef:
        kind: HelmRepository
        name: cilium-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    cluster:
      name: "homeprod"
      id: "1"
    securityContext:
      privileged: true
    kubeProxyReplacement: "strict"
    # kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256
    k8sServiceHost: cranitch.k8s
    k8sServicePort: 6443
    # ipv4NativeRoutingCIDR: 10.10.0.0/116
    ipam:
      mode: "kubernetes"
    containerRuntime:
      integration: containerd
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true
        rollOutPods: true
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/auth-url: |-
              http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
            nginx.ingress.kubernetes.io/auth-signin: |-
              https://hubble.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
            nginx.ingress.kubernetes.io/auth-response-headers: |-
              Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
            nginx.ingress.kubernetes.io/auth-snippet: |
              proxy_set_header X-Forwarded-Host $http_host;
          hosts:
            - &host hubble.${S_HOMEPROD_DOMAIN}
          tls:
            - hosts:
                - *host
    ipv6:
      enabled: false
    bgp:
      enabled: true
      announce:
        loadbalancerIP: true
    cni:
      exclusive: false
