---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 1.6.15
      sourceRef:
        kind: HelmRepository
        name: windmill-labs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    postgresql:
      enabled: false
    windmill:
      baseUrl: "https://windmill.${S_HOMEPROD_DOMAIN}"
        # internalUrl: "http://windmill-app.default.svc.cluster:8000"
      databaseUrl: ${S_WINDMILL_POSTGRES_URL}
      enableOauth: true
      oauthConfig: "{\"cranitchsso\": { \"id\": \"ed5ff4fea4c9ed764d2278e61bbcf70ddfe43e79\", \"secret\": \"1e04734ef12dbe634d05dcd66b2fe934c6611a036faa97f5d507c950cd2436ccfcc8d56ba1f8fa436beca850942b3baa96302b9ae2c7f7c5f62e47fafd665c00\", \"connect_config\": { \"auth_url\": \"https://sso2.cranit.ch/application/o/authorize/\", \"token_url\": \"https://sso2.cranit.ch/application/o/token/\", \"scopes\": [\"openid\", \"profile\"] } } }"
      rustLog: debug
