---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: windmill
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 2.0.416
      sourceRef:
        kind: HelmRepository
        name: windmill-labs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    windmill:
      baseDomain: &host "windmill.${S_HOMEPROD_DOMAIN}"
      baseProtocol: "https"
      databaseUrlSecretName: default-cluster-pguser-windmill
      databaseUrlSecretKey: uri
      app:
        resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 2056Mi
              cpu: 2000m
      workerGroups:
        - name: default
          replicas: 2
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 1028Mi
              cpu: 1000m
        - name: native
          replicas: 2
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m
      lspReplicas: 1
      multiplayerReplicas: 1
    ingress:
      className: nginx
      tls:
        - hosts:
            - *host
