---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: windmill
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 2.0.135
      sourceRef:
        kind: HelmRepository
        name: windmill-labs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    postgresql:
      enabled: false
    windmill:
      baseDomain: &host "windmill.${S_HOMEPROD_DOMAIN}"
      baseProtocol: "https"
      databaseUrl: ${S_WINDMILL_POSTGRES_URL}
    ingress:
      className: nginx
      tls:
        - hosts:
            - *host
