---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 1.7.14
      sourceRef:
        kind: HelmRepository
        name: windmill-labs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    postgresql:
      enabled: false
    windmill:
      baseDomain: &host "windmill.${S_HOMEPROD_DOMAIN}"
      baseProtocol: "https"
      databaseUrl: ${S_WINDMILL_POSTGRES_URL}
      oauthSecretName: windmill-oauth-secret
      workerGroups: []
    ingress:
      className: nginx
      tls:
        - hosts:
            - *host
