---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill
  namespace: windmill
spec:
  interval: 15m
  chart:
    spec:
      chart: windmill
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: windmill-labs-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    postgres:
      enabled: false
    windmill:
      baseUrl: "https://windmill.${S_HOMEPROD_DOMAIN}"
        # internalUrl: "http://windmill-app.default.svc.cluster:8000"
      databaseUrl: ${S_WINDMILL_POSTGRES_URL}
