---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: windmill
resources:
  - helmrelease.yaml
  - secret.sops.yaml
  - namespace.yaml
  - oauth-secret.sops.yaml
configMapGenerator:
  - name: windmill-init-sql
    files:
      - init.sql=./init.sql
generatorOptions:
  disableNameSuffixHash: true
