---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: windmill-pg-initdb
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.3.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image: ghcr.io/onedr0p/postgres-initdb:14.7@sha256:633a7416ba34224caf4d7aac70b6e447c875c9a44d81822c961fcb35d383d23e
    env:
      - name: POSTGRES_HOST
        value: ${POSTGRES_RW_URL}
      - name: POSTGRES_DB
        value: windmill
      - name: POSTGRES_SUPER_PASS
        valueFrom:
          secretKeyRef:
            name: postgres-superuser
            key: password
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: windmill
            key: POSTGRES_USER
      - name: POSTGRES_PASS
        valueFrom:
          secretKeyRef:
            name: windmill
            key: POSTGRES_PASS
