apiVersion: v1
kind: Secret
metadata:
    name: windmill
    namespace: default
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:a/l0I8XOn9E=,iv:+rffULJCAPwrL65zpoLRvVVDZg6q0ms0gw0yQnmjLaU=,tag:BtcrCSVJLONIVzITfWMg4A==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:zfaHt+Hz2/LVK5g4bqDYLCni,iv:Y6z9KufSgaNMyuxevjJdPkW+PudjPdMaFz7YGf1D/GU=,tag:5Md73rDMAm22t1iOb2h3ow==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtUzl6U3VCSUczaDZickZN
            N0ZES1NUNzJoMzYyZTBnZFh0aHAydUl4SkJRClNHMHNLZWFnL0srK09mZWNlYkRB
            MkxmSlRrNUUxdVlQLzU3WUFjaG55UEUKLS0tIEdDRTloSXJ3OHpEUGQ2MGtZVjVI
            YUNFQkkyWHM4bUhaQWxMTENWWjZCMEUKUk1Llh+oAY766lmp6ykBwKlkTOS1uirC
            b+3tDSnaf0jr+SrEoUlHuOBHxIG74ZoEy9cevl5jh97igD/+neGc6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-16T04:12:41Z"
    mac: ENC[AES256_GCM,data:0wUerIAL6ngA/ZydoFlu1ui/tAlIsWKcfKgn4HK85P2ki1JAEM7HSjUIItCgCcVy8mRRtgBktbq66v/f+HUHhNmjI1ymI0S0zMmkDIuU+uqhNfJlWArIfrqAcEgJ2NsGGz+8NOrpwW4Dl43JDaEYxcM3wC0S3JqTaiS9dnuiBEY=,iv:JuxDmddNv+zH2vsX6vlocn5LO3T+VHXOro1n7gZ73QY=,tag:DeYbsVGqstxWyF8D8J7C/w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
