apiVersion: v1
kind: Secret
metadata:
    name: windmill
    namespace: default
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:X7KPHCQdmDk=,iv:IkmuOe+KmkmeX7QyWxCl/Uz3Yx34xwHVvX519piYGGA=,tag:8W2gYBBCmfkYqEZkPFev9w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:8dtFoxmqOqDbmDSckZyHk2ll,iv:S18ikGfAsohMCRDITnnqh68Y2uxBbmBjvprJQkElsYs=,tag:5FV2FZRfyyCeqR9QpheGNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNDV2NnRYYjIxMkEyWnRZ
            NEJtc2xMSFNTVURPNmxJckpwVEVMU3BJYUU4CkRxaGhzVWQ1SzBBTHRXSmM1eEt6
            dE9FU0NSTElOTTRtM3BCQzE5OGZPS00KLS0tIE5qUTd2N2ZYQiszVTZTdjVKbkdV
            ZUpndjgrWUw1NVpJT3M5NlFQOW1ZTkEKdJN++td9Ip3XXX3Jqieq9fwdrFguAbDg
            RIB710yv+IQx+B1ccnVJ8z/1jc7z+TFXKJxiNVXL9f8tl68qKHEQoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-12T08:50:19Z"
    mac: ENC[AES256_GCM,data:Dl/JOHaN1NdBF2Fga50iGABthzrkWSjUpPeHIW8Dxq6OgKsAekR6LtxM+OJb9n0E6ZlysRExnUF7opn2BfLbAYRGG1X66Jex1UmzqUHiwmAyfnHFM1N9qFwL1WnUctSqx36/8Ur3Jzn5nR6sP2JN9DDcxozCefK+coakx9jkmkY=,iv:7SBtMYBF7mi2A0XeYYb546YvOBkIF9EwJOHp/WN/Hxw=,tag:n1mqXjjo9G+tq/zfM2Yg3Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
