---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pgdump-backup
  namespace: database
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    resources:
      - apiVersion: batch/v1
        kind: CronJob
        metadata:
          name: postgres-dump
        spec:
          # run one hour before volsync
          schedule: "0 1 * * *"
          jobTemplate:
            spec:
              backoffLimit: 0
              template:
                spec:
                  containers:
                    - name: dump
                      image: postgres:15.5-alpine@sha256:377da337137b29dff5b82b19fb09fd825253531b3ea7668d1c37eb33e4755fe3
                      volumeMounts:
                        - name: data
                          mountPath: /backup
                      args:
                        - pg_dumpall
                        - "-f"
                        - "/backup/postgres.pgdump"
                        - "-v"
                        - "-h"
                        - ${POSTGRES_RW_URL}
                      env:
                        - name: PGUSER
                          valueFrom:
                            secretKeyRef:
                              name: postgres-superuser
                              key: username
                        - name: PGPASSWORD
                          valueFrom:
                            secretKeyRef:
                              name: postgres-superuser
                              key: password
                  restartPolicy: Never
                  volumes:
                    - name: data
                      persistentVolumeClaim:
                        claimName: pgdump
