---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdump
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
