---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tailscale
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/tailscale/tailscale
              tag: v1.54.1
            envFrom:
              - secretRef:
                  name: tailscale
            env:
              TZ: ${TZ}
              NO_AUTOUPDATE: 'true'
              TS_USERSPACE: 'true'
              TS_KUBE_SECRET: tailscale-state
              TS_ROUTES: 192.168.29.0/24
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
    service:
      main:
        enabled: false
    serviceAccount:
      name: tailscale
