apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tailscale-connector
  namespace: networking
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: tailscale-connector
