apiVersion: v1
kind: Secret
metadata:
    name: operator-oauth
    namespace: networking
stringData:
    client_id: ENC[AES256_GCM,data:xah4APBGQO6cGdOsv2Oi8UA=,iv:6WLEurc6H/FKPgaW3sgb9wdbWL+7jlLRD+KHvRIIrdY=,tag:CCi1xYRWQgW3EUI4+UP5dQ==,type:str]
    client_secret: ENC[AES256_GCM,data:iTosNfKCzKbN41rIrhk4hWpP40yFwg71ouq+qa87Z6OAKfgdn7Jw9tTVnYqkB94risMF8sMYLX3EDuZ/amnjhA==,iv:DiZ0NZ4MYKmO0aBkdC1DOBFCBdV6b0r0zIR5lO3xzhE=,tag:UW9cVuvWG/k+bYyMzW55+A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxWWhuV1hVYXFGTk9MTndP
            Nkg2SytuYU84UjVmS29aYTh3WG1TeWh6akhnCkplN2JCbEZIQURtTStBSXluRlZK
            MGJJK2JYMG03WEhvQzVHcFEwN3pDRjQKLS0tIGtZd3QxUHgyZW43enBTTGV3Qmhr
            cGw5WDZyMS9yZm9SN3dSUjZuNGZaUjgKixxlzL4QUe7yAfMbbRc1nYGzGlLrr6RG
            P9jWIzG+pHHc7SKOC6IiHqc1RVJX5CTNaTlGZkWrR5GIrfV+TPoKsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T10:38:47Z"
    mac: ENC[AES256_GCM,data:JbTwNZh5dYWLhC2C7RCsDbhxplWfJjxrA9qbh8lWeCCAP+fR4fGCTKqOkOYRBH/yhvN0PTydhY7VkQtZL57Kp09Vn+1SYIsk57M7BA9WC+1in7S4lt6G9sPwWO+KAh1eM5WB7MQHdpBIngl8D9xKSVPCwiXt1due0PCnAKm4JO8=,iv:dfOpk9xcd0+FMwbUEy+iyGrY34KgTNPhQ5qJGebTOFM=,tag:ZzxTTR1c1oH6W5/7jXnmeQ==,type:str]
    version: 3.13.1
