apiVersion: v1
kind: Secret
metadata:
    name: tailscale
    namespace: default
stringData:
    authkey: ENC[AES256_GCM,data:BFAFpxZdydjpZT9ElU2F/ApoXNIx2ZUdQRqkWmgjxFujlvgMXMicowEGxhRXz46Zaj9CaZO3O8s=,iv:8Vm4iMPGE2vaoQwSOuDUqEH9ekStOj2kxK0ib9zVO6o=,tag:vNu9TOLHniG7Iri5/9PC+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXRkL3FaMkgybVBLZ0lZ
            K2hFaG1rWGdpSHZmMmdjWmo1eVVOcDZPQ1c4Ck1iNGlxSkdLVG5FdVlwVGthRGVu
            REJBNWpVK1VXNDg3aTdvTjdjeWxTZ3cKLS0tIHNZeFNyNXYvNWE0TVdtWndEZytK
            OE90MWErSVdRdUVNT0U3WVNnVW5KMTQK0KbzxXlNtFtJGPavyfl9bpaeuSBA3DtJ
            N/AKD4ilUMNAr1h1X5+MYQl+A8b5ahp+u5mcF6s1IT8jCly8vj4JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-17T06:09:49Z"
    mac: ENC[AES256_GCM,data:RFrG4sZOa6yVVeLIKhiYXLDXv7GnGzqu7q2DVMavQ9sByBhlRX/A5AwoKD8+fSJn8i26BdQxWqqDvS8Kwgbv+ifGloinVS4/uw2yly78qizh8f+nPVLTZUkuVJcjz47aycr/XjTTdyq3g3hUYe8WCmz9SJb9rLVXFefVQugCdRU=,iv:sut6UjkGPiQ2M//GI26aZBbD+mtMVqMUvCaeGL+613Q=,tag:GgNMsYIR7oMnn6yD+/EOBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
