apiVersion: v1
kind: Secret
metadata:
    name: tailscale
    namespace: networking
stringData:
    TS_AUTH_KEY: ENC[AES256_GCM,data:7MJNdsp/TSu7h0cYKc7Vwf5Y6sD4RuElvw7+J82KsYyR198LHH8YQfgc3Av/VRyPShOdLP770fsmyBiPEsJDmDPHFHvgWF6L2JaBNmDD,iv:jkwR+Gd4gRWg/m7LktGBVgKjd/ZmT91Nj+PT2EusOAU=,tag:tSlMgJbSSdhJUwLza7cOUQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXRkL3FaMkgybVBLZ0lZ
            K2hFaG1rWGdpSHZmMmdjWmo1eVVOcDZPQ1c4Ck1iNGlxSkdLVG5FdVlwVGthRGVu
            REJBNWpVK1VXNDg3aTdvTjdjeWxTZ3cKLS0tIHNZeFNyNXYvNWE0TVdtWndEZytK
            OE90MWErSVdRdUVNT0U3WVNnVW5KMTQK0KbzxXlNtFtJGPavyfl9bpaeuSBA3DtJ
            N/AKD4ilUMNAr1h1X5+MYQl+A8b5ahp+u5mcF6s1IT8jCly8vj4JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-02T10:15:07Z"
    mac: ENC[AES256_GCM,data:+Yjx0HhmfrMbLtIhSQBUczSvRvhGWZDlEyDviwk94FqdXyO7OEPEDUiDC9Mn/ncHAEbxTiWI5nwNwNHh9b7mASeEb/+4pBvOb2FcC17cyxQ1UWFBZHtIj1izkvBFEpQl6xBWts60+ll4OYSo5FNTzztexbgaRtIwimbOBtj9TSQ=,iv:wnQvaagKPfNqNFi0+5mEbiUhUB/vPZIutKVT/ECBGpA=,tag:Ser1fl9mKXm5iJr7ZftHoA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
