---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-serverlan
  namespace: networking
spec:
  config: |-
    {
      "cniVersion": "1.0.0",
      "master": "bond0",
      "mode": "bridge",
      "type": "macvlan",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.29.0/24",
        "rangeStart": "192.168.29.150",
        "rangeEnd": "192.168.29.159",
        "routes": [
          { "dst": "192.168.29.0/24", "gw": "192.168.29.1" }
        ]
      }
    }

