---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zigbee2mqtt
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 1Gi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: zigbee2mqtt-destination
