---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: multus
  namespace: networking
spec:
  interval: 15m
  chart:
    spec:
      chart: multus
      version: 5.0.4
      sourceRef:
        kind: HelmRepository
        name: angelnu-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/k8snetworkplumbingwg/multus-cni
      tag: v4.0.2-thick
    cni:
      image:
        repository: ghcr.io/angelnu/cni-plugins
        tag: 1.4.0
      paths:
        config: /etc/cni/net.d
        bin: /opt/cni/bin
    hostPaths:
      netns: /var/run/netns
