---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iotlan
  namespace: networking
spec:
  # host-local maintains a local database of allocated IPs
  # TODO: need to set the appropriate vlan
  config: |-
    {
      "cniVersion": "1.0.0",
      "master": "eth1",
      "mode": "bridge",
      "type": "macvlan",
      "ipam": {
        "type": "host-local",
        "subnet": "192.168.13.0/24",
        "rangeStart": "192.168.13.200",
        "rangeEnd": "192.168.13.210",
        "routes": [
          { "dst": "192.168.13.0/24", "gw": "192.168.13.1" }
        ]
      }
    }

