---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-typesense
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/typesense/typesense
              tag: 0.25.1
            envFrom:
              - secretRef:
                  name: immich
              - configMapRef:
                  name: immich
            probes:
              liveness: &id001
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 8108
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *id001
              startup:
                enabled: false
    service:
      main:
        ports:
          http:
            port: 8108
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
        storageClass: ceph-block
        globalMounts:
          - path: /config
