---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ocis
  namespace: ocis
spec:
  interval: 15m
  chart:
    spec:
      chart: ./charts/ocis
      version: 0.4.0
      sourceRef:
        kind: GitRepository
        name: ocis-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    externalDomain: &host files.${S_HOMEPROD_DOMAIN}
    # TODO: cache:
    # TODO: store:
    http:
      cors:
        allow_origins:
          - sso2.cranit.ch
    features:
      externalUserManagement:
        enabled: true
        oidc:
          issuerURI: https://sso2.cranit.ch/application/o/ocis/
          webClientID: 1a075b256031b7f352fa1b08569a557a3be35ef2
          userIDClaim: email
          roleAssignment:
            enabled: true
            claim: groups
            mapping:
              - role_name: admin
                claim_value: service-admins
              - role_name: user
                claim_value: service-users


    # TODO: securityContext: (set to values for nfs)
    # TODO: services:
    #         idm:
    #           persistence:
    #         nats:
    #           persistence:
    #         search:
    #           extractor:
    #             type: tika????
    #           persistence:
    #         storagesystem:
    #           persistence:
    #         storageusers:
    #           persistence:
    #         store:
    #           persistence:
    #         thumbnails:
    #           persistence:
    #         web:
    #           ????
    #           persistence:
    ingress:
      enabled: true
      ingressClassName: nginx
      tls:
        - hosts:
            - *host
    # TODO:
    # monitoring:
    #   enabled: true
