---
apiVersion: authentik.starry.blue/v1alpha1
kind: AuthentikApplication
metadata:
  name: windmill
  namespace: default
spec:
  slug: windmill
  name: Windmill
  adopt: IfMatch
  deletionPolicy: Delete
  provider:
    name: Windmill
    flows:
      authorization:
        slug: default-provider-authorization-implicit-consent
      invalidation:
        slug: default-provider-invalidation-flow
      authentication:
        slug: authentication-flow
    oauth2:
      clientType: Confidential
      redirectURIs:
        - url: https://windmill.${S_HOMEPROD_DOMAIN}/user/login_callback/authentik
      scopes:
        - scopeName: openid
        - scopeName: email
        - scopeName: profile
      grantTypes:
        - AuthorizationCode
        - Hybrid
        - Implicit
        - ClientCredentials
        - Password
        - DeviceCode
        - RefreshToken
      accessTokenValidity: minutes=5
      signingKey:
        name: authentik Self-signed Certificate
  access:
    public: true
    prune: true
