---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-operator
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-operator
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    serviceMonitor:
      create: true
    web:
      ingress:
        enabled: true
        className: nginx
        hosts:
          - host: flux.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - flux.${S_HOMEPROD_DOMAIN}
