---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: linkding
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/sissbruecker/linkding
              tag: 1.38.0
            env:
              LD_SUPERUSER_NAME: tom
              LD_ENABLE_AUTH_PROXY: "True"
              LD_AUTH_PROXY_USERNAME_HEADER: HTTP_X_AUTHENTIK_USERNAME
              # TODO: LD_AUTH_PROXY_LOGOUT_URL: todo
              LD_CSRF_TRUSTED_ORIGINS: https://bookmarks.${S_HOMEPROD_DOMAIN}
              LD_DB_ENGINE: postgres
              LD_DB_HOST:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-linkding
                    key: host
              LD_DB_DATABASE:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-linkding
                    key: dbname
              LD_DB_USER:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-linkding
                    key: user
              LD_DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-linkding
                    key: password
    service:
      main:
        ports:
          http:
            port: 9090
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://bookmarks.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host bookmarks.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /etc/linkding/data
