apiVersion: v1
kind: Secret
metadata:
    name: linkding
    namespace: default
stringData:
    LD_DB_PASSWORD: ENC[AES256_GCM,data:Hkg4d7a9K3uenIukzSrW7NX2hTooNFyyaLp94uWE,iv:dBVjvOQdj8Vq9CJA/KtcnzThwGPjmk99RziDQC3656I=,tag:8kebj635iFAiBsPGZUULgg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UbLY7Bkwz9Y=,iv:zArrivebbhQ5u2Q8wVlFKYusjjmdroa4PjtmrIwtaFw=,tag:oSJRg/2TYpIKAYrX9mtfYw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:hKKENeua5j8=,iv:L79WyzU2Au7elpf0RJwaquxkbrKyeere2OpfJLkm3qU=,tag:2DCINIdakB2NBsjQajOwEw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:DZcaWhkrPJRUHOaj+Klw/yGN4nx/h4elgQDAK00W,iv:sYpCCVI0JuvUIYKmi/FLOclmKWpwujhnPBBzpDzfHgM=,tag:L74/vntrkv+KuCZvIlBRwA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc3Q2NXBDcXN3aG4wSk9a
            SEdIalJQYzRPTFJXQ0JQVTEreER2UHlEUHljCnFLZVZqdTNtQ0xjbWlVZ0YwVFZV
            dFBNWjdjMkRuOEhMK0JLcHlId1dhZU0KLS0tIFBETFRQRU5Dem1uTWYvU1lORkNP
            WEhPTTdUWmhaZ1JqU2lYNjJNKzJ3amsKMXonjNEcYFI0Wfb1Fa/VxQ7So4qbYoy6
            qSFenKtn4u4yVU1KJpiiQR3cxCbdtrxdLoiRzSi/sEKrY/VCyiR4Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T02:37:21Z"
    mac: ENC[AES256_GCM,data:/MhXLWyZp6PV4egNE/kdS1HLkTLu42Tcn1KwPLwTRKLlwi9CF1QJVzNNqqJsW59nmWHBt5yhZZe0qhGMa/NMe9WH6wyZ2DHZC24bXGn/WZhYF4/J85a4JzxS3obSdwQObyEhgZ9Zmr0e06A2k4wt/JC2+4/TvEff3dx7oeWBIz8=,iv:oMsFSBKwEIwRf2Yk2himsy3yO9H7ImBeXQEzgXuKSfM=,tag:bvsyOtqcaEEeM3qh1OAT8A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
