apiVersion: v1
kind: Secret
metadata:
    name: linkding
    namespace: default
stringData:
    LD_DB_PASSWORD: ENC[AES256_GCM,data:Hkg4d7a9K3uenIukzSrW7NX2hTooNFyyaLp94uWE,iv:dBVjvOQdj8Vq9CJA/KtcnzThwGPjmk99RziDQC3656I=,tag:8kebj635iFAiBsPGZUULgg==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:2PaxWttS3E4=,iv:nlmNP0Knsf+SNwUfGS9jCC+G6NmU8ezV1PD3f6yEWZc=,tag:Pzy9JQl+l1awSvSbroS+jw==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:Qy0ItQaNcf8=,iv:d8VDDIu7A2ivZ7CxsomQMS7J6z6Ps4MdyQjrM8OIN70=,tag:pORmHZZQwUFRZHz+KqKf8w==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:gfOkorH4twgM28NAfYyxPjSCtVeWdkit5o0KkY4F,iv:oNFlWr3S1QNuA0IfCEfIQT1QqJVBcCSJgmYiGEC47Yw=,tag:YtqwmgyBClxY9O3sogJd1Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwc3Q2NXBDcXN3aG4wSk9a
            SEdIalJQYzRPTFJXQ0JQVTEreER2UHlEUHljCnFLZVZqdTNtQ0xjbWlVZ0YwVFZV
            dFBNWjdjMkRuOEhMK0JLcHlId1dhZU0KLS0tIFBETFRQRU5Dem1uTWYvU1lORkNP
            WEhPTTdUWmhaZ1JqU2lYNjJNKzJ3amsKMXonjNEcYFI0Wfb1Fa/VxQ7So4qbYoy6
            qSFenKtn4u4yVU1KJpiiQR3cxCbdtrxdLoiRzSi/sEKrY/VCyiR4Wg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-02T04:54:43Z"
    mac: ENC[AES256_GCM,data:ZQLKqcQZNgv+tupoL4xB142e94DW/grcMsg3WL60xhElpwQZPQSx0RZfxCe734XCZJyS6XVSo6tGGwu3l7SwAfwcJtMs3XaHN3ogxGe8ZHx7ZzdHMliiFUeasmme6rUDNeMjiZnNZFXexwy3Tv2eSp0m0FfZhWF4h60HnTkdYLs=,iv:lzoIpq9HhoNcsv/rM5yuwZ+BHMCK4hgNqzhqoj1jhJM=,tag:X781/9CYc0QXwLlgf1eTWQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
