---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: digitalocean-issuer
  namespace: ingress
spec:
  acme:
    email: "${S_DIGITALOCEAN_EMAIL}"
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: homeprod-domain-cert
    solvers:
      - dns01:
          digitalocean: 
            tokenSecretRef:
              name: digitalocean-dns
              key: digitalocean-access-token
