apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: digitalocean-issuer
  namespace: ingress
spec:
  acme:
    email: ${S_EMAIL}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    solvers:
      - dns01:
          digitalocean: 
            tokenSecretRef:
              name: digitalocean-dns
              key: digitalocean-access-token
