---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: flux-instance
  namespace: flux-system
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: flux-instance
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    instance:
      distribution:
        version: 2.7.5
        registry: ghcr.io/fluxcd
      components:
        - source-controller
        - kustomize-controller
        - helm-controller
        - notification-controller
      cluster:
        type: kubernetes
        multitenant: false
        networkPolicy: true
        domain: cluster.local
      sync:
        kind: GitRepository
        url: ssh://git@github.com/TomCranitch/homelab.git
        ref: refs/heads/main
        path: cluster/flux
        pullSecret: flux-system
      kustomize:
        patches:
          - patch: |
              - op: add
                path: /spec/decryption
                value:
                  provider: sops
                  secretRef:
                    name: sops-age
            target:
              kind: Kustomization
          - target:
              kind: Kustomization
              name: flux-system
            patch: |
              apiVersion: kustomize.toolkit.fluxcd.io/v1
              kind: Kustomization
              metadata:
                name: flux-system
                namespace: flux-system
              spec:
                postBuild:
                  substituteFrom:
                    - kind: ConfigMap
                      name: cluster-settings
                    - kind: Secret
                      name: cluster-secrets
