---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: database
spec:
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  interval: 15m
  dependsOn:
    - name: cnpg
      namespace: database
  values:
    resources:
      - apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: cnpg-cluster
          namespace: database
        spec:
          instances: 3
          imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.2.1
          primaryUpdateStrategy: unsupervised
          storage:
            size: 15Gi
            storageClass: ceph-block
          superuserSecret:
            name: postgres-superuser
          enableSuperuserAccess: true
          postgresql:
            parameters:
              timezone: ${TZ}
            shared_preload_libraries:
             - "vectors.so"
          monitoring:
            enablePodMonitor: true
          # backup:
          #   retentionPolicy: 30d
          #   barmanObjectStore:
          #     data:
          #       compression: bzip2
          #     wal:
          #       compression: bzip2
          #       maxParallel: 4
          #     destinationPath: s3://homeprod-cnpg
          #     endpointURL:  https://s3.us-east-005.backblazeb2.com 
          #     # serverName: 
          #     s3Credentials:
          #       accessKeyId:
          #         name: postgres-s3
          #         key: key-id
          #       secretAccessKey:
          #         name: postgres-s3
          #         key: app-key
          bootstrap:
            recovery:
              source: clusterBackup
          externalClusters:
            - name: clusterBackup
              barmanObjectStore:
                destinationPath: s3://homeprod-cnpg
                endpointURL:  https://s3.us-east-005.backblazeb2.com 
                # serverName: 
                s3Credentials:
                  accessKeyId:
                    name: postgres-s3
                    key: key-id
                  secretAccessKey:
                    name: postgres-s3
                    key: app-key
