---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg-cluster
  namespace: database
spec:
  chart:
    spec:
      chart: raw
      version: v0.3.1
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 15m
  dependsOn:
    - name: cnpg
      namespace: database
  values:
    resources:
      - apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        spec:
          instances: 3
          primaryUpdateStrategy: unsupervised
          storage:
            size: 15Gi
            storageClass: ceph-block
          superuserSecret:
            name: postgres-superuser
          postgresql:
            parameters:
              timezone: ${TZ}
          monitoring:
            enablePodMonitor: true
