---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: database
spec:
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  interval: 15m
  dependsOn:
    - name: cnpg
      namespace: database
    values:
    resources:
      - apiVersion: postgresql.cnpg.io/v1
        kind: Cluster
        metadata:
          name: postgres
          namespace: *namespace
          annotations:
            kyverno.io/ignore: "true"
        spec:
          instances: 3
          primaryUpdateStrategy: unsupervised
          storage:
            size: 15Gi
            storageClass: ceph-block
          superuserSecret:
            name: postgres-superuser
          postgresql:
            parameters:
              timezone: ${TZ}
          monitoring:
            enablePodMonitor: true
