# Makes a backup of the whole db to make point in time restores faster
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: cnpg-cluster
spec:
  schedule: "0 3 * * *"
  immediate: true
  backupOwnerReference: self
  cluster:
    name: cnpg-cluster
