---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: victoria-logs
  namespace: monitoring
spec:
  description: Allow log ingestion, Grafana queries, Envoy and metrics
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: victoria-logs
  ingress:
    - fromEndpoints:
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: fluent-bit
            app.kubernetes.io/instance: fluent-bit
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app: grafana
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: ingress
            app.kubernetes.io/name: envoy
            gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
        - matchLabels:
            k8s:io.kubernetes.pod.namespace: monitoring
            app.kubernetes.io/name: vmagent
      toPorts:
        - ports:
            - port: "9428"
              protocol: TCP
  enableDefaultDeny:
    ingress: true
    egress: true
  log:
    value: victoria-logs
