apiVersion: v1
kind: Secret
metadata:
  name: konflate-secret
  namespace: default
type: Opaque
stringData:
  KONFLATE_APP_PRIVATE_KEY: ""
  KONFLATE_WEBHOOK_SECRET: ""
  KONFLATE_APP_ID: ""
  KONFLATE_INSTALLATION_ID: ""
