apiVersion: tailscale.com/v1alpha1
kind: ProxyClass
metadata:
  name: connector-spread
spec:
  statefulSet:
    pod:
      labels:
        app.kubernetes.io/component: tailscale-connector
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 2
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/component: tailscale-connector
      tailscaleContainer:
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            memory: 128Mi
  metrics:
    enable: true
    serviceMonitor:
      enable: true
