---
apiVersion: v1
kind: Secret
metadata:
  name: reader-lowpriv-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: reader-lowpriv
type: kubernetes.io/service-account-token
