---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc
  namespace: rook-ceph
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: rook-ceph-dashboard
  oidc:
    provider:
      issuer: "https://sso.${S_HOMEPROD_DOMAIN}/application/o/gateway/"
    clientID: "8lRVJAKvaAvnGZVcrSVtFbMkmpLBQoauOi0fOuAZ"
    clientSecret:
      name: envoy-oidc-secret
    redirectURL: "https://zigbee.${S_HOMEPROD_DOMAIN}/oauth2/callback"
    logoutPath: "/oauth2/logout"
    cookieDomain: "${S_HOMEPROD_DOMAIN}"
