apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
    namespace: default
stringData:
    client-secret: ENC[AES256_GCM,data:Ck9UozEMzILv/p9F+1zgAbORPaA2nXgwpIHtLIyk5Czqcwx83Rr6T8G27P5crhRQz2xWtgON5ZVQmSE9EmWl6QBYws09R/GcnRKvJi6lYnWoAol5kTQ9jGckRV9SrliHzbjQQYHFemknpAv8aqSyDoi4K9pan/ZwRm6VIymkyN0=,iv:pit9QZk9b8l+JINtL6NDUowb2ZdtK1Q+hUknuuppOQs=,tag:Yinim7ZCMJKgQBoEjMGFNg==,type:str]
sops:
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5WVB6V2ZTbWp0alZvZGd3
            Yy9HNWdCZUVTNHRFc2FUMDB0bzU0WE51V0NBCmMreUkrNTBac2x4NUxvdHRzTU4v
            Wkc3a05jcnNzOHJFbEx6dkQxNWFBWVEKLS0tIEhzditWeG51S0hzaTBtWm04Q3Bh
            akNVWS9GckJHaDNPc2IyK09VVTZuVm8KlRqTXZKocmq5MrQxpAC8moaitP1eXQEg
            E17JeZvYpCOD6KrxE/+gt1EahG0IXi/bazKjBBWXyo/AVNIp9DFHYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T12:04:58Z"
    mac: ENC[AES256_GCM,data:S5bTAZFL3pcdMzj1HnmKCm9Kq+2Qft3oX/JIwhKuDgVPS5fVYJ3hSc8tozka7CW3ZZNGRt0f0JtGBmgyG48ZDn4eMOEP+nkXRP7Eh8kaddHzUYyH+tnEilJ03GZaM2XIs/URKnaAz50eZ0Fy4KLVPiD/WXq79YWX3FBGLwsBlfI=,iv:6mpQxp0GQBWyvTUTyZD6i3DBQSHVyHgmZyz+JKUsnFk=,tag:+G+wx6wJsszdZx/DMh0Ktg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
