apiVersion: v1
kind: Secret
metadata:
    name: authentik-operator-token
    namespace: default
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:r+yf2h0tIVBOdEPwCxMEY2m3Khu4vX9BsQNfDtRVliDwuE2NjlgpMgBnHS9kAalLwdBxsmnpOTxhUsi+,iv:WTwSJkOFJjQgXyKwBxo8+l5Nblb2pBjp0kLnzah1dao=,tag:9aSqP/s1i9hOCT4asta/Rw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeFR6a3ExOGJkMk16dklW
            K0NoZWE2UWt2NFV0MmpnSi9wRjRwZDBOWHljCjlTMVc1SFNKaThyNjl6SFpNUzQ3
            KzlLT0hpejRMQnk0Q20yQkFOTmRHSlUKLS0tIDlDamhnZUFXbmJjaGg0OW8ybksx
            dHVzY1pJL3lxS3YvRmtZV2JmR091UmMKwD04W95yB4q9FUVXFUT8/gQX4kEDubC8
            dlZGLWr4/6zeIQNj+uL4LJskF3AWFwV300oId1VkKCumxnqzr1oEig==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:51:13Z"
    mac: ENC[AES256_GCM,data:DIbG7A9R+n+turEQvvI6a6F6ogVU4XeGuuCEfUmDivGdc0Jq+ytWpWYjsQJ8zSh8u1YHSuI1w9S6yZI4zXhIib6BePLYwxaOpRGkvJnKrUDQH5CT7W9JQhtgjzym51FZPY8LcfezTICbDOvaS9HJgOnLHCokyjoyNygrZL1vw3A=,iv:VSSCtjmcV4uXFQEJYVoCC1mpr3PctF0y/gbUoNDsXXM=,tag:SpkzXtyxOjMYjcaWesEMGw==,type:str]
    version: 3.13.1
