---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: Always
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/onedr0p/home-assistant
              tag: 2024.10.4
            envFrom:
              - secretRef:
                  name: home-assistant
            env:
              TZ: ${TZ}
          code:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.95.2
            env:
              TZ: ${TZ}
              GIT_AUTHOR_NAME: Tom Cranitch
            workingDir: /config
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name": "multus-serverlan",
                "namespace": "networking"
              }]
    service:
      main:
        ports:
          http:
            port: 8123
      code:
        controller: main
        ports:
          http:
            port: 8081
    ingress:
      main:
        enabled: true
        # annotations:
        #   nginx.ingress.kubernetes.io/auth-url: |-
        #     http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
        #   nginx.ingress.kubernetes.io/auth-signin: |-
        #     https://home.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
        #   nginx.ingress.kubernetes.io/auth-response-headers: |-
        #     Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
        #   nginx.ingress.kubernetes.io/auth-snippet: |
        #     proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - host: &host home.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
      code:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://hass-code.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        ingressClassName: nginx
        hosts:
          # TODO protect with reverse proxy auth
          - host: &hass-code hass-code.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: code
                  port: http
        tls:
          - hosts:
              - *hass-code
      # auth-outpost:
      #   enabled: true
      #   ingressClassName: nginx
      #   host:
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant
        globalMounts:
          - path: /config
    podAnnotations:
      # TODO: switch to IOTLan (to hopefully help with mdns)
      # Using IOTLan was causing connectivity issues with google home hub/esphome
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name": "multus-serverlan",
          "namespace": "networking"
        }]
