---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8@sha256:0141cf427c47f2d534711a3f9e8c5f9008bc6b585463ccd9288cf0f027e20deb
        env:
          - name: POSTGRES_HOST
            value: ${POSTGRES_RW_URL}
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
        envFrom:
          - secretRef:
              name: home-assistant
    image:
      repository: ghcr.io/onedr0p/home-assistant
      tag: 2023.7.3
    podAnnotations:
      # TODO: switch to IOTLan (to hopefully help with mdns)
      # Using IOTLan was causing connectivity issues with google home hub/esphome
      k8s.v1.cni.cncf.io/networks: |
        [{
          "name":"multus-serverlan",
          "namespace": "networking"
        }]
    env:
      TZ: ${TZ}
    envFrom:
      - secretRef:
          name: home-assistant
    persistence:
      config:
        enabled: true
        existingClaim: home-assistant
        mountPath: /config
    service:
      main:
        ports:
          http:
            port: &port 8123
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "home.${S_HOMEPROD_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      # TODO switch to OnRootMismatch
      fsGroupChangePolicy: "Always"
    addons:
      codeserver:
        enabled: true
        image:
          repository: ghcr.io/coder/code-server
          tag: 4.16.1
        env:
          TZ: ${TZ}
          GIT_AUTHOR_NAME: Tom Cranitch
        workingDir: '/config'
        args:
          - --auth
          - 'none'
          - --user-data-dir
          - '/config/.vscode'
          - --extensions-dir
          - '/config/.vscode'
        ingress:
          enabled: true
          ingressClassName: 'nginx'
          annotations:
            # TODO: this isnt working
            # nginx.ingress.kubernetes.io/auth-url: |-
            #     http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
            # nginx.ingress.kubernetes.io/auth-signin: |-
            #     https://sso.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
            # nginx.ingress.kubernetes.io/auth-response-headers: |-
            #     Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
            # nginx.ingress.kubernetes.io/auth-snippet: |
            #     proxy_set_header X-Forwarded-Host $http_host;
          hosts:
            - host: &host-code "hass-code.${S_HOMEPROD_DOMAIN}"
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - hosts:
                - *host-code
        volumeMounts:
          - name: config
            mountPath: /config
