apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: default
stringData:
    INIT_POSTGRES_DB_NAME: ENC[AES256_GCM,data:lCog3g==,iv:dzsQCrE4+uOLuIabez+io/YBprBxKI0GCtiKHwKLgdo=,tag:IoJLSt3z/Vh3+O4AFxOCUA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:2PW+yA==,iv:gm/eT11LDO/kDL74RdqNx7tmKXjaSe9LqdkV5Q5uczI=,tag:Zl/d/eAxvWcYV17/9eV3og==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:LJXz+ck4K1YmqiNyrdQNWO1XVpnn2TdW1wYVDRREWJAKQpjvLcMfpQ==,iv:aax2i3Iq/YohqNoSpx4i071QJWnNQxMa8c5uwjKqnJY=,tag:B0X4ibEtXzzPROu9r3oWVg==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:UQ7XX9k+EwDdTCK0Ts9kMRHu1BqTBLLmMpFrjU2f5oY9uEvU7hO0QheuC6Th1SSdbx3uAhUnHCEqxg3ucc6Zz6vf4rExP5UCDmi+tkZGGy3e7+ep0H5jih3vWFI=,iv:ndG/akWtGjtJ2EM4SmVUB9risUbvPhsSthQtqPpY4lk=,tag:HisWSi2wp/K1fH20SVVXGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXRkL3FaMkgybVBLZ0lZ
            K2hFaG1rWGdpSHZmMmdjWmo1eVVOcDZPQ1c4Ck1iNGlxSkdLVG5FdVlwVGthRGVu
            REJBNWpVK1VXNDg3aTdvTjdjeWxTZ3cKLS0tIHNZeFNyNXYvNWE0TVdtWndEZytK
            OE90MWErSVdRdUVNT0U3WVNnVW5KMTQK0KbzxXlNtFtJGPavyfl9bpaeuSBA3DtJ
            N/AKD4ilUMNAr1h1X5+MYQl+A8b5ahp+u5mcF6s1IT8jCly8vj4JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-20T02:30:12Z"
    mac: ENC[AES256_GCM,data:484ovHaUq68WB/NjcK/7YQgUmcKrv9VDPTZ8tn5eiKqBHb4jyDe3isVmGBm/SNt2OtEfjCqR4KZmh9FdI2lVq1ddKk4p/apdj/nqblGpMh9mLPM8qmUgqLiaylEiRz614QbXN0Jmk0Kr9Q1J3GEksExplfC3+y6e0VwnqaRX9Yw=,iv:utgFxB8W1OwSmbmunL/FjPvLcmm/EWhPyV6m+qgtSUE=,tag:EI27vxu8xHIGHmxh/oET2Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
