apiVersion: v1
kind: Secret
metadata:
    name: home-assistant
    namespace: default
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:a00qwg==,iv:MaRGOyPYR13Xq+FM8erCWDlcybAz5+UauBohxyH0I5M=,tag:lz2ixv2++nRoSZtqchzR/A==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:jNJmwQ==,iv:uIZUc25nbDcpGzNG20tVlrWkeRu62FSbCybn1JYgxCo=,tag:mUHnJOLb4pY3btCUNw8RBw==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:8H+qFzpZjP+VQdp1nuhqNI+Ye5JuIUiJEuVv6pGpzUjLE4LpUpu3iw==,iv:pgjjKH2xov+Bn+FOze9GrHc5FN/0VfwI0rkmeoe6+vw=,tag:Z7u6XSKGxTzK8ASrr5p4eg==,type:str]
    HASS_POSTGRES_URL: ENC[AES256_GCM,data:UQ7XX9k+EwDdTCK0Ts9kMRHu1BqTBLLmMpFrjU2f5oY9uEvU7hO0QheuC6Th1SSdbx3uAhUnHCEqxg3ucc6Zz6vf4rExP5UCDmi+tkZGGy3e7+ep0H5jih3vWFI=,iv:ndG/akWtGjtJ2EM4SmVUB9risUbvPhsSthQtqPpY4lk=,tag:HisWSi2wp/K1fH20SVVXGA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJQXRkL3FaMkgybVBLZ0lZ
            K2hFaG1rWGdpSHZmMmdjWmo1eVVOcDZPQ1c4Ck1iNGlxSkdLVG5FdVlwVGthRGVu
            REJBNWpVK1VXNDg3aTdvTjdjeWxTZ3cKLS0tIHNZeFNyNXYvNWE0TVdtWndEZytK
            OE90MWErSVdRdUVNT0U3WVNnVW5KMTQK0KbzxXlNtFtJGPavyfl9bpaeuSBA3DtJ
            N/AKD4ilUMNAr1h1X5+MYQl+A8b5ahp+u5mcF6s1IT8jCly8vj4JAA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-25T03:52:26Z"
    mac: ENC[AES256_GCM,data:5ZTwBwmXcvUU0PwOQPdQ1Q7nI4YZftoikb76F7wAC1c1rXIAcaQaqVkFx+XK4fcefXPN34fuEPbIy6PIGFk+N2DTUdKXA4bmzlaFB8Zo/llCQh1EH3TipsXVW7VWdJHyt/Ugc5vPb+SBxKnhicQTP18/CbXzEHcL/eDupXmjxxo=,iv:+QZ+6GIIFKRHd/imu30HqSBBQxKokr/ijSYWoTNV/9A=,tag:+VX1IZ+cTXvroo1ZXjBUYA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
