---
apiVersion: v1
kind: Secret
metadata:
  name: home-assistant-restic
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${S_VOLSYNC_B2_REPO}-home-assistant
  RESTIC_PASSWORD: ${S_VOLSYNC_B2_PASSWORD}
  B2_ACCOUNT_ID: ${S_VOLSYNC_B2_ID}
  B2_ACCOUNT_KEY: ${S_VOLSYNC_B2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: home-assistant-restic
  namespace: default
spec:
  sourcePVC: home-assistant
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: home-assistant-restic
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 111
      runAsGroup: 111
      fsGroup: 111
    retain:
      daily: 7
      weekly: 6
      monthly: 6
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: home-assistant-destination
spec:
  trigger:
    manual: restore-once
  restic:
    repository: home-assistant-restic
    copyMethod: Snapshot # must be Snapshot
    volumeSnapshotClassName: csi-ceph-blockpool
    # cacheStorageClassName: ceph-block
    # cacheAccessModes: ReadWriteOnce
    cacheCapacity: 2Gi
    storageClassName: ceph-block
    accessModes: ReadWriteOnce
    capacity: 1Gi  # TODO: keep in sync with pvc
