apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    S_HOMEPROD_DOMAIN: ENC[AES256_GCM,data:vE1jPCbctxjjSFD9IQ/+tzE=,iv:H36roipiYENqlcJw+HsBRkfamScdUyN1ne+PAIdw2fo=,tag:Q2kcCnUN2QfqU9VQtZ5Rzw==,type:str]
    S_DIGITALOCEAN_EMAIL: ENC[AES256_GCM,data:i30+zvsbcrJCt1tXi63iQwr5wsA=,iv:rrgz/7L1LnZ7LGh+augiAJNCtuhpGsnuX/PoqnjI/5I=,tag:uPobzynJqe7BgeLjoaRpiw==,type:str]
    S_GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:2DSRurHRUmsSyIGWzngr0g80iJFBVbFBtOOwCpxo5xSaKuAVkDYdag==,iv:da2QwLQfjxOCrzmS3zf6PGcMIXWUXdVunaqteDwaoto=,tag:iyy3TTXwDquQHd4mD6bL2w==,type:str]
    S_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:vjyWq7ccaXQHbCmhJfPKOEQhmhGrv987FeXX+9hwTyPKqHclpvbEvRSyWSFPGPRyG25FDWRSXOQuZ6IwGxwBL0gnCPzLoZmNWWOMLd3+n6I6pR5pj8yUbN77OkENd2yT2a1N0YDFVNmGuKV9nIfNm7+SUu9EaCw/xYZoZAucCBE=,iv:53/lKz2ROPvUTr8/L3KaPEzeX3bYWlgLOVioXDCU1wo=,tag:uL5m8QCVkH9Q4ANQrfO6/w==,type:str]
    S_BASE_DOMAIN: ENC[AES256_GCM,data:x7EYFc/3gznv,iv:y/Y8EIkw5wXTczWiQ0WpxXA5kEK3dTEvX5RN+kHTGkg=,tag:9rT0AI+jjxO8u3bExN8YLA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLOUJVNTJEZGlHOEs3MnpR
            aytQdmdwYk82Tzg5NjY0djduZkpaWGVRM0dRCnNvTUdpYTJGM0RwTnNOYW0xQzYv
            ZzdTdTY5YkJCWEl6VlkxcCt4c2NLcDAKLS0tIHJScnJIOEQwZ3pkQ3UwQVI0WWM1
            QW1WcGEvQUkzQ2tvcU11ekFOMWFrZDgKlzIv6cXyln/dk7CR94RcNLo1pKkBNQff
            Nis3lDRCXwP822cldZYSCkcNCVyii/NcBU3CY/muf6RXZxLOfJmplQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-15T02:08:57Z"
    mac: ENC[AES256_GCM,data:vCQkPe5jeLJc0meWm/V53r96ITorIazPjx1EgOaZN6o8f2EWr52efeNCxMcEUSQSYSzzloNF1lT0PMpPuOXRenv3JTpW+CAvJHiMubnxs88qAIM8mgyI4vjPJ5Fmt7QQylQK3QWt+OtYC4ok66yRpx0D5LyIybI93tsJoFcFb44=,iv:cxTp2F3KGxU5MvF1wauXkGvnYMp7UwZpFc8hfqOjHMk=,tag:HhmF8u6oqhHTMGJsQSTtmw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
