apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    S_HOMEPROD_DOMAIN: ENC[AES256_GCM,data:y6Jyfq8pQrZkODZcS5gh+EI=,iv:qWdfNvpb0UGfMVGGKkxlvpclaZu3emTzm8vhXdDtr8M=,tag:/se5yK+D4/gF2p5lddVDVQ==,type:str]
    S_BASE_DOMAIN: ENC[AES256_GCM,data:ZmGzu1nekTmd,iv:7z5/niCXInFfx0h/3TrrSfJ6/GcvY++FzG3cJdZSjQ4=,tag:Y6YjShdJMUUIFoyX/sUdhA==,type:str]
    S_NFS_SERVER: ENC[AES256_GCM,data:UJPeMvywj6i9f1RuQxk=,iv:N/9IPXS0B9nHY0eAFqZeFf0xFhujOPeWbeJ0QcqP+xo=,tag:1XuCFIh3wlV4oZ5e+52Dtw==,type:str]
    S_DIGITALOCEAN_EMAIL: ENC[AES256_GCM,data:yMal1Iy7wsNWnIdvErk00tU90KY=,iv:qZ3CSe+nB2UGjDd3EmIvZfUC7rInYjmlMPjhZporyVA=,tag:VNGCQ5iTIfpXDrMiFGj5Yg==,type:str]
    S_GRAFANA_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:hpm55OYB3AUYHtSZ//jdlBXIOMc9cOsRd0B0M9pu0paieVqk5bYkzA==,iv:5VQJs94YwwaZHiS2CRlYJUx2wklxLlxTxP4cywtSRxY=,tag:j8mUuUOknllzxWRsYc/+Sg==,type:str]
    S_GRAFANA_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:3wStTLSH6CvwZyxCezObV9JXDRU7KUKeOdskqYvC5PlBEVvN3bYLrMdwWz0rH9qFwWeS+c6HaO4LcpYC8FUcwcdCr6fnCy+f/ET4v8vnF9b4ztQcn1KQ8zTLzQQleaC3mrBzZG5FExKEm6O847EEH+YyySUu5HXGPM1mEAYxnkc=,iv:qAEQpP61N8JO7cZvMtJWGzRFLEkk77vyw4KIrJIawaU=,tag:PNVMUHzKdBrlePI1XR6++A==,type:str]
    S_VALETUDO_AUTH_HEADER: ENC[AES256_GCM,data:l8IDMhNisutT93Jg+XhjC0Ce3V5Gypnj+BJIigfyW5AWTUozLGlJYA==,iv:qfqqUPn8PGVm5ykcp4IbYwT9psLHL154eyFUo/UMvXo=,tag:FvDxQvzLWfucffVM/0ThHQ==,type:str]
    S_WINDMILL_POSTGRES_URL: ENC[AES256_GCM,data:MbV+UuV1gN3k94JSshCUnxUAsdR7bBdATtTH8IYM2aCLUJgkl3MZANUWSG78w4XMLsz+ueen4ZIzXt6n/HRtPzNiBYO5lNgne36GPqCL,iv:8WfxZ8itNP2XEuxLa9/uBnkl+IpaIRHViKG3XlN0AYY=,tag:VOcQ7MzqWxqr1bP7/rlN+g==,type:str]
    S_VOLSYNC_B2_REPO: ENC[AES256_GCM,data:C+Eht4apDYR2MM4KbBRHRxhvrDxsYry9C1RNoyP8GiaB,iv:s+ag5JXOZcXwQ1Xi+RxsspXfOIe28YksY6qyulCNH5s=,tag:vBfY39wdn+/jWKecGwJOIg==,type:str]
    S_VOLSYNC_B2_PASSWORD: ENC[AES256_GCM,data:JoOnXTH36RWe9YGyDsMEmE7yrZ59uAv77wxhZ2FZ,iv:3XqVlYT1xUjFW08HZyK/QH1xv46UY2CPt4nesaxMHr8=,tag:2i58n2I8RE//Qn9QYHEeww==,type:str]
    S_VOLSYNC_B2_ID: ENC[AES256_GCM,data:S9vSvcyRm29RUWAoPNdlIQ/08ydtmMnP2w==,iv:lUSE8Dy+wwormO+CTKQ667akYuuiyYUCU4tX6UhGuCY=,tag:KLL8IfWv23gRtNUSykU91g==,type:str]
    S_VOLSYNC_B2_KEY: ENC[AES256_GCM,data:zLd3/+vFcCMoHiqzP9YW1y+39FVyo12pvo6zbTm6ZQ==,iv:K7JKAph5Wqjo/O9dbGJAHgefs2YhdIvgkqMHYOFS6Rc=,tag:gtdVLDVHGTwg5SQ0KTQt0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMUFQaWpEWEQ5ZzZkUXJQ
            S1M5S1JjcTBYbVBETTdxbmMrQUJnQnZrN0djCnhDQ002L1dSVTVTdnlZSHo0dzg4
            V3JZL1MvSFVDdDNXQmdHSnhIZTI4V1kKLS0tIGp0YktmSEM4T3MzeWQyUG4veE41
            eHRoL1lBdlhQdEVFUEUxQ0pnSm1tNXcKwNjDptSY2zMWspG26JYc9FpAAbsU/Y3i
            7SV3w6QNLO9nJW3rxmysU477TGHQTZ4N2zCFk1LfBqJiHxQL6wGx+A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-04-23T11:37:54Z"
    mac: ENC[AES256_GCM,data:PlqlZalfK34KA+GNLQWOcErHQOWgumeY+PSvYMxYC7VH8U8/iYw2/YIWZLcBqiJbEPHYRX3F0dwIxqzIJNJcDZPKxCyRPI8IH54mnQu1mnf/g99hXuHoouL90VZscHpQTsbAnBdBPIeLzwT/Riw6bnzmA0Xo9v3v/+fgjpSET4M=,iv:TDbie8MIchy8AiDUs0LWNvIuBgPgyagR/CI1PgXd9RE=,tag:6O41C2I/+ltc6WcNfgNvyg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
