apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    S_HOMEPROD_DOMAIN: ENC[AES256_GCM,data:235px9B5Fuvb,iv:n2qeK8RHlbukgGRxWMNs6dygJJQ43Dths/XbGHOYQlo=,tag:LSUVFD+ETLyFT3BiAFWnNQ==,type:str]
    S_DIGITAL_OCEAN_ACCESS_TOKEN: ENC[AES256_GCM,data:e8tv/AFHY1cZsAXlzRMiQ8RG6F4zBqcPlpSDHq5V66zIxDUWeOQqmahZkZQ6yKkCaCpKbBdV2YDWDp3q9HkxEO0aWRQNQe4j0UcPQ3o0PY1RHX+Q5d3jtqx/MYmVaPP1,iv:8uYnuWVtFqLCfCWVddUIoa3WCBI/UJoqIYkTvYXG2zY=,tag:DJ/182aoOtq0oWc8j9+jEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6WGpJWEVad3A0eDdtSGVk
            a2RXZi82dFZvL1JVZTQvNDFHa3BJM1lqMEZnCnUvTHZOaGVmZnpBejB5T1N3L3ZS
            N3RTWHB1U1c1M2twU3h6VDdlUzEvc28KLS0tIHZZSHpBSVptdFYxUHZPcGltbFRi
            ZWdWK1NOa3BNZlE3ajEyV2dsczlEZGcKz8o3R1khXKXq/pj5RUU+5LrqXqGWWYrO
            2XJp4WbFQJfiGPXFZEHaWHVpoxG8p8p3YYkbvb1/FIrttU/cM/TKaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T12:23:28Z"
    mac: ENC[AES256_GCM,data:V+ZfF+0Ux3QiJc3FYckgb17Pqjx9OPQayZ35S/V47a6x/kw9kXEQIVgckVo92nHcivt7ILrX/5kLLl5tF5Cq1FWK1bZNpNEaPlYcjaNZhPtw+Kn4nRCENrFQGyW/AN/kXECo1xOktGOyQIL/Mc6ZBJrl8G82gsBDgivpa9xBIKc=,iv:UPUbyHepHF3ABj6dcR5Ig240dtiAtAIihii3xxpOuuo=,tag:fe5d41cWtrwKFsNIc04ubw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
