apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
data:
    S_HOMEPROD_DOMAIN: ENC[AES256_GCM,data:mbRvn0t7gdITgwSQ,iv:IusNTwHDO9ITYs2DvDIKSTUvTgT9pPmNscvUwwgMvdA=,tag:zypsUce22gfCxlFS5hAI9w==,type:str]
    S_DIGITAL_OCEAN_ACCESS_TOKEN: ENC[AES256_GCM,data:Samr9++E+ePffKirSs4/HJ7z0nXpwzWAYsvQnNITFl8rBFCt/qddVQjMLhrv+mIcKfinfC26NbLPAaiUrNm7r86vrUSM9IJXseed5wSj+1yLLph51krxwvwFHEleqJdA,iv:YXwCFRoe8Anf/dxYPsSUZuVzvETWLE/HAoR96+gPHUY=,tag:8Idz/dfZJ4ueE1GN6gVrVw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvN3hnZWFINzIvWStiTDBD
            QTFDc1JVTG91Uyt6dnA2NW1qdjdnL092b2xBCld3L2g5RkhGLzVXMWN1SVN0K3Mz
            b0ttSDdGZ2lOYkFDVTRSMXVqRzZ5NDAKLS0tIGM1Wk41Vm54aTI2bWZnclN2aTRp
            bmR6Ti8zVHYvSDNUclh6cXVvdi9KZHMKdOId+aeAnXSDIgIlFGhO7uD7fS44zRzI
            ilNrz6/6VFOt7PGc8wILtdKDnVkwE/cGw8iEQYnsZ1ZJcJeKVSoZdg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-09-05T12:25:36Z"
    mac: ENC[AES256_GCM,data:jApi0hV10WG2kAtMrCIRUwAYELkPap9TSjDyTV0uoTZEJ+FazdWsj3SsSwr1JDCI3/WptCHwlrkTsvUhBReoWOx2ubDnd4UYS5egTk2eFc3+G5xgHm/kUDPdnAT2+ziB9dpng2ci8Ecs903W6Ayz3Zinhwpk7+53A4hbdlRCT6A=,iv:typdd8G1RWb/ydHfqd7DiHTgA71RDMMwsKO+4XIQKmA=,tag:2zKRAwVqJMancxh1PtgWrw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
