---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SSO_DOMAIN_PREFIX: sso
  TZ: Australia/Sydney
  POSTGRES_RW_URL: postgres-ha.database.svc

  # TODO this is wrong ;(
  LB_EMQX: 10.10.1.50

  CONTAINER_UID: "1000"
  CONTAINER_GID: "100"

  # renovate: datasource=docker depName=ghcr.io/siderolabs/installer
  TALOS_VERSION: v1.3.6
  # renovate: datasource=docker depName=ghcr.io/siderolabs/kubelet
  KUBERNETES_VERSION: v1.26.2
