---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SSO_DOMAIN_PREFIX: sso
  TZ: Australia/Sydney
  POSTGRES_RW_URL: postgres-ha.database.svc

  # TODO this is wrong ;(
  LB_EMQX: 10.10.1.50

  CONTAINER_UID: "1000"
  CONTAINER_GID: "100"
