---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  SSO_DOMAIN_PREFIX: sso
  TZ: Australia/Sydney
  POSTGRES_RW_URL: cnpg-cluster-rw.database.svc

  LB_EMQX: 10.10.1.50
