---
apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: default-cluster
  namespace: default
  labels:
    crunchy-userinit.ramblurr.github.com/enabled: "true"
    crunchy-userinit.ramblurr.github.com/superuser: "postgres"
spec:
  postgresVersion: 16
  instances:
    - name: postgres
      replicas: 3
      dataVolumeClaimSpec:
        storageClassName: ceph-block
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 15Gi
  patroni:
    dynamicConfiguration:
      synchronous_mode: true
      postgresql:
        synchronous_commit: "on"
  users:
    - name: postgres
      databases:
        - postgres
      password: 
        type: AlphaNumeric
    - name: authentik
      databases:
        - authentik
      password: 
        type: AlphaNumeric
    - name: linkding
      databases:
        - linkding
      password: 
        type: AlphaNumeric
    - name: mealie
      databases:
        - mealie
      password: 
        type: AlphaNumeric
    - name: paperless
      databases:
        - paperless
      password: 
        type: AlphaNumeric
    - name: vaultwarden
      databases:
        - vaultwarden
      password: 
        type: AlphaNumeric
  backups:
    pgbackrest:
      configuration:
        - secret:
            name: crunchy-backup-secret
      repos:
        - name: repo1
          s3:
            bucket: homeprod-crunchy
            endpoint: https://s3.us-east-005.backblazeb2.com
            region: us-east-005
          schedules:
            full: "0 3 * * 2"
            differential: "0 4 * * *"
            incremental: "0/15 * * * *"
      global:
        repo1-retention-diff: "21"
        repo1-retention-full: "120"
        repo1-retention-full-type: time
        repo1-path: /default/
      manual:
        repoName: repo1
        options:
          - --type=full
  
  # TODO: datasource
  # TODO: proxy.pgBouncer
