---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden
  - mealie
  - immich
  # Requires running script here: https://docs.windmill.dev/docs/advanced/self_host#run-windmill-without-using-a-postgres-superuser
# - windmill
