---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - vaultwarden
  - immich
  - windmill
  - ocis
  - mealie
  - home-assistant
  - esphome
  - authentik
  - pgmqtt
  - zigbee2mqtt
  - ntfy
  - linkding
  - karakeep
