# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: esphome
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 5.0.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${CONTAINER_UID}
        runAsGroup: ${CONTAINER_GID}
        fsGroup: ${CONTAINER_FSGROUP}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      esphome:
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        containers:
          app:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2025.12.7
            env:
              PLATFORMIO_CORE_DIR: /cache/platformio
              PLATFORMIO_GLOBALLIB_DIR: /cache/platformio/lib
              PLATFORMIO_SETTING_ENABLE_TELEMETRY: No
              PIP_CACHE_DIR: /cache/pip
              XDG_CACHE_HOME: /cache
              TZ: ${TZ}
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
        pod:
          annotations:
            k8s.v1.cni.cncf.io/networks: |
              [{
                "name": "multus-iotlan",
                "namespace": "networking",
                "ips": ["192.168.13.10/24"]
              }]
    service:
      app:
        controller: esphome
        ports:
          http:
            port: 6052
    route:
      main:
        enabled: true
        kind: HTTPRoute
        hostnames:
          - "esphome.${S_HOMEPROD_DOMAIN}"
        parentRefs:
          - name: envoy-gateway
            namespace: ingress
    persistence:
      config:
        enabled: true
        existingClaim: esphome
        globalMounts:
          - path: /config
      cache:
        type: emptyDir
        globalMounts:
          - path: /config/.esphome
          - path: /cache
            subPath: cache
