---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: database
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised
  storage:
    size: 15Gi
    storageClass: ceph-block
  superuserSecret:
    name: postgres-superuser
  postgresql:
    parameters:
      max_connections: "100"
      shared_buffers: "256MB"
      timezone: ${TZ}
  monitoring:
    enablePodMonitor: true
