---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kguardian
resources:
  - ocirepository.yaml
  - helmrelease.yaml
  - httproutes.yaml
  - securitypolicy.yaml
  - mcp-secret.sops.yaml
  - oidc-secret.sops.yaml
