apiVersion: v1
kind: Secret
metadata:
    name: kguardian-mcp-token
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:0j7mHd4/On3gt8n3X6Rqm7cS/hJ40ociHcIgoZagD1gIbVA8mgsleMHdbBBR/55h3ApyviwU39lYbL78uD1hQA==,iv:whG2KMpud0Jw30XVsicNDS4yJeVjnEMwlL8iqwr3bk0=,tag:u+0jd/nIeIbj603yBdceOw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCMEpWSWJ0MjFzenhVVC9H
            UmNoYUpRM3hod0R2Q3dROENZMUdGamhRaVhBCkJ2VTg3OWU3R0FLQlpSNFJMNDRp
            TDFPYXhqQU92SFU5bkcvYUtkYzhpbTQKLS0tIFNNeEQ4YzU4MXRhRGYxNXBJbTlL
            T1Q3RmZPMnZBaUNETFAxWHhyUDRqczgKAkLxmKKyOBe4Ck+JfQ34cfq3xQ+EMSAn
            9CCHa01vLS67KNPj8NFmqSz9W7iJRKOaW1c49WKkuSlfS4UfM0MpgA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T10:20:44Z"
    mac: ENC[AES256_GCM,data:Cit2yonAT9k/Ih2B+I3rXBLip+F46qvIRMmpxb/LXA5rvnHwBjw9TYPp16gR44+HzwyPfiXOezEJUHI6QU1K6VWS7sQjgUmy9DD1ZuwUUmX1xPTnDN10izwtrZ8+xP/vzUQnIMhJW0t/9jLdI2bXh5uuQDAhyTiCIVccJ7jMIcY=,iv:BeOmlfQzCcID9840OLRNiM4SSK6YXXYfbmZnTIqh300=,tag:+fLmNuLdFOlfGlt6zH4kgg==,type:str]
    version: 3.13.1
