apiVersion: v1
kind: Secret
metadata:
    name: envoy-oidc-secret
type: Opaque
stringData:
    client-secret: ENC[AES256_GCM,data:doknU7ADf+cDY0DlhVkZBPMVnP/elyxQwylG03FyBlGgnPOmrPJYZagVzGk7J4qZyBPa/C9MLur4m2KYy3K4gl26mvQYYi85p7VyUlx5izT87NIrKZDoDHYQd0EQ/rJ5wx7YJf/bq3bVEbjGqKzj5/tMIfTirXvOoEA1ysCVc2w=,iv:+KMppNZ0moqhH3cXCmhiN/TUhPzpvr2zhbB+95lX3cE=,tag:gwfGMqlHPM6/VmduUDtiyw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SGZUdGpORkU1a3hTcE85
            TXV1amtQTUMrS2dqN0lpMlNDN0RjdUdWVDE4CnI5OWpFc3pIRlJ3OGE5ckNmKzcz
            UFpRSnVzVWZ2SWpiSzRaeTFHTStnbzQKLS0tIGRTRjR1V3VCVHlqSjNNeGFHdVBh
            Wk1GWWpuQ1hxMDNXL2lMWUtTUk1SV1kK5h1DPw08JKQjhH8qDDhaw5dikYGBk45y
            A3H7dDX7dkErUg9E2rtybAEHrS2kSHLEjNwUd76sHERtXJEYx6d26g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-16T10:21:06Z"
    mac: ENC[AES256_GCM,data:nqHs7PelwssKHOqpKGoKPrJyRK2kqFDTCI2Fnt8CIfTGfqFWqvz4xvixoo75Va/tNgzXj84ps8adauoL68XfVCZO0qbHhhSJulmHAY2laCoyKFNOS7OIB8meiVGxwBWR17LytSXoQVvt521YbgzWGbNaxBN53feAd+tOPs/b93M=,iv:p7rvP9utnYRDu1bf6tGOm/GUtk76OhEvaiLhY/1qasY=,tag:7JRuo4IScFmqT9IHSpPNsg==,type:str]
    version: 3.13.1
