# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich-redis
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      "immich-redis":
        containers:
          app:
            image:
              repository: public.ecr.aws/docker/library/redis
              tag: 8.2.1
            env:
              REDIS_REPLICATION_MODE: master
            command: redis-server
            probes:
              liveness:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
              readiness:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
              startup:
                enabled: true
                spec:
                  tcpSocket:
                    port: 6379
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: "immich-redis"
        ports:
          http:
            port: 6379