---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ntfy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.2.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: docker.io/binwiederhier/ntfy
      tag: v1.30.1
    env:
      TZ: ${TIMEZONE}
      NTFY_DEBUG: false
      NTFY_BASE_URL: https://notifications.${S_HOMEPROD_DOMAIN}
    args: [serve]
    persistence:
      cache:
        enabled: true
        type: pvc
        size: 1Gi
        accessMode: ReadWriteOnce
        mountPath: /var/cache/ntfy
    service:
      main:
        ports:
          http:
            port: 80
      # smtp:
      #   enabled: true
      #   ports:
      #     smtp:
      #       enabled: true
      #       port: 25
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        hosts:
          - host: &host "notifications.${S_HOMEPROD_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
