---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: kyverno
      version: 3.2.3
      sourceRef:
        kind: HelmRepository
        name: kyverno-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    installCRDs: true
    backgroundController:
      resources:
        limits:
          memory: "256Mi"
