---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # TODO this renovate comment doesnt work. also should group together
  # TODO if possible move to CRDs installed from chart
  # renovate: registryUrl=https://kyverno.github.io/kyverno/ chart=kyverno
  - github.com/kyverno/kyverno//config/crds?ref=kyverno-chart-2.7.2
  - helmrelease.yaml
  - rbac.yaml
  - namespace.yaml
  - policies
