---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kyverno-policies
  namespace: kyverno
spec:
  interval: 15m
  chart:
    spec:
      chart: raw
      version: v0.3.2
      sourceRef:
        kind: HelmRepository
        name: dysnix-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: kyverno
      namespace: kyverno
  values:
    resources:
      - apiVersion: kyverno.io/v1
        kind: ClusterPolicy
        metadata:
          name: sync-postgres-superuser-secret
          annotations:
            policies.kyverno.io/title: Sync Postgres Superuser Secret
            policies.kyverno.io/subject: Secret
            policies.kyverno.io/description: >-
              This policy will copy a secret called `postgres-superuser` which
              exists in the `database` namespace to new namespaces when they are
              created. It will also push updates to the copied Secrets should the
              source secret be changed.
        spec:
          # mutateExistingOnPolicyUpdate: true
          generateExistingOnPolicyUpdate: true
          rules:
            - name: sync-postgres-superuser-secret
              match:
                resources:
                  kinds: 
                    - Namespace
              generate:
                apiVersion: v1
                kind: Secret
                name: postgres-superuser
                namespace: "{{request.object.metadata.name}}"
                synchronize: true
                clone:
                  namespace: database
                  name: postgres-superuser
      # TODO: move to kustomization patch
      - apiVersion: kyverno.io/v1
        kind: ClusterPolicy
        metadata:
          name: add-postgres-init-db
          annotations:
            policies.kyverno.io/title: Add postgress init db
            policies.kyverno.io/subject: Pod
            policies.kyverno.io/description: >-
              Add the postgres init-db init container to the pod.
        spec:
          # mutateExistingOnPolicyUpdate: true
          generateExistingOnPolicyUpdate: true
          rules:
            - name: windmill-init-db
              match:
                resources:
                  kinds: 
                    - Pod
                  names:
                    - "windmill-*"
              mutate:
                patchStrategicMerge:
                  spec:
                    volumes:
                      - name: init-sql
                        configMap:
                          name: windmill-init-sql
                    initContainers:
                      - name: init-db
                        image: ghcr.io/tomcranitch/postgres-init-with-sql:0.0.1@sha256:5511526d94123153cb09eaf7e9e8ab42ad80eda988fc40fb51956443bb334c00
                        volumeMounts:
                          - name: init-sql
                            mountPath: /etc/init.sql
                            subPath: init.sql
                        env:
                          - name: POSTGRES_HOST
                            value: ${POSTGRES_RW_URL}
                          - name: POSTGRES_DB
                            value: windmill
                          - name: POSTGRES_SUPER_PASS
                            valueFrom:
                              secretKeyRef:
                                name: postgres-superuser
                                key: password
                          - name: POSTGRES_USER
                            valueFrom:
                              secretKeyRef:
                                name: windmill
                                key: POSTGRES_USER
                          - name: POSTGRES_PASS
                            valueFrom:
                              secretKeyRef:
                                name: windmill
                                key: POSTGRES_PASS
                          - name: POSTGRES_INIT_FILE
                            value:  /etc/init.sql
