---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-server
  namespace: flux-system
spec:
  targetNamespace: default
  path: ./cluster/apps/ingress/echo-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: echo-authentik
  namespace: flux-system
spec:
  targetNamespace: default
  dependsOn:
    - name: authentik-operator
  path: ./cluster/apps/ingress/echo-server/authentik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  healthCheckExprs:
    - apiVersion: authentik.starry.blue/v1alpha1
      kind: AuthentikApplication
      current: >-
        has(status.observedGeneration) &&
        status.observedGeneration == metadata.generation &&
        has(status.conditions) &&
        status.conditions.exists(c, c.type == 'Ready' && c.status == 'True' &&
          c.observedGeneration == metadata.generation)
  interval: 30m
  retryInterval: 1m
  timeout: 5m
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
