---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/apps
  prune: true
  dependsOn:
    - name: core
  sourceRef:
    kind: GitRepository
    name: flux-cluster
