---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 10m
  path: ./cluster/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: crds
    - name: charts
# TODO secrets/config map (e.g. https://github.com/toboshii/home-ops/blob/main/cluster/flux/core.yaml)
