---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ntfy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.0.2
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.8.0
            env:
              TZ: ${TIMEZONE}
              NTFY_DEBUG: false
              NTFY_BASE_URL: https://notifications.${S_HOMEPROD_DOMAIN}
            args:
              - serve
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        hosts:
          - host: &host notifications.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      cache:
        type: pvc
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/cache/ntfy
    serviceMonitor:
      enabled: true
      endpoints:
        - port: http
          path: /metrics
          interval: 1m
          scrapeTimeout: 10s
