---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.9.0
            env:
              TZ: ${TIMEZONE}
              NTFY_DEBUG: false
              NTFY_BASE_URL: https://notifications.${S_HOMEPROD_DOMAIN}
              # TODO: change port
              NTFY_METRICS_LISTEN_HTTP: :9090
            args:
              - serve
    service:
      main:
        ports:
          http:
            port: 80
          metrics:
            port: 9090
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host notifications.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/cache/ntfy
    serviceMonitor:
      main:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s
