# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ntfy
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${CONTAINER_UID}
        runAsGroup: ${CONTAINER_GID}
        fsGroup: ${CONTAINER_FSGROUP}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      ntfy:
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        containers:
          app:
            image:
              repository: docker.io/binwiederhier/ntfy
              tag: v2.14.0
            env:
              TZ: ${TIMEZONE}
              NTFY_DEBUG: false
              NTFY_BASE_URL: https://notifications.${S_HOMEPROD_DOMAIN}
              # TODO: change port
              NTFY_METRICS_LISTEN_HTTP: :9090
            args:
              - serve
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
    service:
      app:
        controller: ntfy
        ports:
          http:
            port: 80
          metrics:
            port: 9090
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host notifications.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      cache:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /var/cache/ntfy
    serviceMonitor:
      app:
        enabled: true
        endpoints:
          - port: metrics
            scheme: http
            path: /metrics
            interval: 1m
            scrapeTimeout: 10s