---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: ingress
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: ingress
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    deployment:
      replicas: 2
      pod:
        topologySpreadConstraints:
          - maxSkew: 1
            minDomains: 2
            topologyKey: kubernetes.io/hostname
            whenUnsatisfiable: DoNotSchedule
            nodeTaintsPolicy: Honor
            matchLabelKeys:
              - pod-template-hash
            labelSelector:
              matchLabels:
                control-plane: envoy-gateway
    podDisruptionBudget:
      minAvailable: 1
