---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: ingress
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
    namespace: ingress
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    deployment:
      replicas: 2
      envoyGateway:
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
      pod:
        affinity:
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    control-plane: envoy-gateway
    podDisruptionBudget:
      minAvailable: 1
