---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/mealie-recipes/mealie
              tag: v1.12.0
            env:
              TZ: ${TZ}
              API_URL: "http://mealie-backend.default.svc.cluster.local:9000"
              BASE_URL: https://recipes.${S_HOMEPROD_DOMAIN}
              DB_ENGINE: postgres
              OIDC_AUTH_ENABLED: "True"
              OIDC_CONFIGURATION_URL: https://sso.cranit.ch/application/o/mealie/.well-known/openid-configuration
              OIDC_CLIENT_ID: 2xgDOa0vZ0LOkhMf8H3xnbZxeKO9s0iNBq8zBgqk
              OIDC_ADMIN_GROUP: service-admins
              OIDC_AUTO_REDIRECT: "True"
              OIDC_PROVIDER_NAME: "Cranitch SSO"
              POSTGRES_PORT: 
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-mealie
                    key: port
              POSTGRES_SERVER:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-mealie
                    key: host
              POSTGRES_DB:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-mealie
                    key: dbname
              POSTGRES_USER:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-mealie
                    key: user
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-mealie
                    key: password
    service:
      main:
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        hosts:
          - host: &host recipes.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      config:
        enabled: true
        existingClaim: mealie
        globalMounts:
          - path: /app/data
