# TODO: no guarantee this works - not tested on app-template v2
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mealie
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/hkotel/mealie
              tag: frontend-v1.0.0beta-5
            env:
              TZ: ${TZ}
              API_URL: "http://mealie-api.default.svc.cluster.local:9000"
      backend:
        initContainers:
          01-init-db:
            image: ghcr.io/onedr0p/postgres-init:14.8
            env:
              - name: INIT_POSTGRES_HOST
                value: ${POSTGRES_RW_URL}
              - name: INIT_POSTGRES_DB_NAME
                value: mealie
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: postgres-superuser
                    key: password
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: mealie
                    key: POSTGRES_USER
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: mealie
                    key: POSTGRES_PASSWORD
        containers:
          main:
            image:
              repository: docker.io/hkotel/mealie
              tag: api-v1.0.0beta-5
            env:
              TZ: ${TZ}
              DB_ENGINE: postgres
              POSTGRES_SERVER: ${POSTGRES_RW_URL}
              POSTGRES_PORT: 5432
              POSTGRES_DB: mealie 
              BASE_URL: https://recipes.${S_HOMEPROD_DOMAIN}
            envFrom:
              - secretRef:
                  name: mealie
    service:
      main:
        ports:
          http:
            port: 3000
      backend:
        ports:
          http:
            port: 9000
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-body-size: "50m"
        hosts:
          - host: &host recipes.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      config:
        enabled: true
        existingClaim: mealie
        globalMounts:
          - path: /app/data
