---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
  namespace: default
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: spegel
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    grafanaDashboard:
      enabled: true
    service:
      registry:
        hostPort: 29999
    serviceMonitor:
      enabled: true
    spegel:
      containerdSock: /run/containerd/containerd.sock
      containerdRegistryConfigPath: /etc/cri/conf.d/hosts
