---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth-select-all
  namespace: monitoring
spec:
  # TODO???? 
  # ...
  # provide access to all users
  selectAllByDefault: true
  ingress:
      class_name: "nginx"
      # Secret filled in by cert manager
      # tlsSecretName: vmauth-external-tls-secret
      tlsHosts:
        - vmauth-external.${S_HOMEPROD_DOMAIN}
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-proxmox
  namespace: monitoring
spec:
  tokenRef:
    name: vmuser-secret
    key: proxmox
  targetRefs:
    - crd:
        kind: VMAgent
        name: victoria-metrics-k8s-stack
        namespace: monitoring
      paths: ["/.*"]  # TODO
