---
apiVersion: v1
kind: ConfigMap
metadata:
  name: immich
  namespace: default
data:
  DB_PORT: "5432"
  DB_DATABASE_NAME: immich
  DB_HOSTNAME: ${POSTGRES_RW_URL}
  DISABLE_REVERSE_GEOCODING: "true"
  ENABLE_MAPBOX: "false"
  LOG_LEVEL: verbose
  NODE_ENV: "production"
  REDIS_HOSTNAME: immich-redis.default.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_DBINDEX: "10"
  TYPESENSE_HOST: immich-typesense.default.svc.cluster.local
  TYPESENSE_DATA_DIR: /config
  TYPESENSE_PORT: "8108"
  TYPESENSE_PROTOCOL: http
  IMMICH_WEB_URL: http://immich-web.default.svc.cluster.local:3000
  IMMICH_SERVER_URL: http://immich-server.default.svc.cluster.local:3001
  IMMICH_MACHINE_LEARNING_URL: http://immich-machine-learning.default.svc.cluster.local:3003
