apiVersion: v1
kind: Secret
metadata:
    name: immich
    namespace: default
stringData:
    DB_USERNAME: ENC[AES256_GCM,data:CCqQdhDa,iv:Cu7L0nXo5L53fBRnHhlAQZrmmm+lrrRpeOVHq+gE5e0=,tag:gBtHqxzzZotE2ZAJQ8EUVQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:LPwYhQoNP5B91QDWerZ0rzNny04+MxpAKWl6hpDOfDpEU78GMGuLf7+F+bwpO8p/ZoPvhrbzvHszzGNFPh04uPG6fH8NMjjhyITkQjuKoyQ3bNsdfxZr1k1WC9BRkeWqjlSAe9QCJDCqjxvaMU8rpjgCIGECChejwZwEbWb7bmAZ8pScm3871utFLzVu9tl8xGB0vF9PJI1ij61tE0Ks6ksqsIeCfZMClngowA==,iv:2PlB7c6Wzukg0p093f/Zlr0otErUUa1QW3jn0sjhTao=,tag:rekg8+5Pa0OLLzHkSK152A==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:hUZjisjjgnFviGoKwck0Aprg9NyhpHHSQRZpdcus7NydZ2hYEmPHCPCrzYs1rYGq9sseWck6EbmtqFZgwumING3QvdQmfXpaYHsgvc3JRRuy86bJyvDKuZ4AvUf7mpjlZ1fmSF4eMkr9rXRvGIET8ZYh0Xifhcrngc1Tu2VAHfG79qMTdZrjTud60/barOyz2yK/VHOYIcaB9F5OZnN58ICZMmJAFpxqCvxETw==,iv:gX24SEVioFAMS1mMALl07SjFkLMdJ9iTwC27DKU8AfY=,tag:OcKVYE9EqgPpnNmK2ozK2g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwYXArbVgvSFNBdXRiZVJw
            MUdKYXlDaEhLTGpJQ214d2IzVDJJNnhBUVJZCnBjRnVsZDJJZGdlMXdTNUgwZXFw
            UUNKdmRRTG1EdkhObHZkYzZMOTNvSVUKLS0tIFdwb0FBS2I0WlAvOHprY3VidGFQ
            clhKS2FGdDBvd1BwTmdqeFF1Q0p4RGMKS/VDJ0y8VU0m6Dd1deAfIU2QbizvE6J2
            J4yCgE/GG+h8s0Y3wO2eRdw7jAN1H+TzP66aTSmTMnRYnUlBnrEM2A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-20T09:37:36Z"
    mac: ENC[AES256_GCM,data:+HR91X5Q3IbcCidyRs1r8mv16TLaEA6dfaa3cjkrBMCD0cvpKhCHRr2CJV56EEqehvv0axWcStdl1IRiF301jNd81AD8UpfsOqEp1lWbPGrcpsYrsWKYjXZ8MG3J4e7Kqfj7u+7G2Ggo8ZdQLG91ORTMiDC4Lw8wyra1T9tnfzo=,iv:yQLtKtKbQb1WL3DgTgFT/86MuxmEEuGFJAGrzZ7TIXo=,tag:x9XbPz69BOOdkuVkjp36hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
