---
apiVersion: v1
kind: Secret
metadata:
  name: immich-restic
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${S_VOLSYNC_B2_REPO}-immich
  RESTIC_PASSWORD: ${S_VOLSYNC_B2_PASSWORD}
  B2_ACCOUNT_ID: ${S_VOLSYNC_B2_ID}
  B2_ACCOUNT_KEY: ${S_VOLSYNC_B2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-restic
  namespace: default
spec:
  sourcePVC: immich-nfs-pvc
  trigger:
    schedule: "0 2 * * *"
    manual: immich-manual-sync-trigger
  restic:
    # TODO consider moving to an nfs provisoner (e.g. democratic-csi) which supports snapshots
    copyMethod: Direct
    pruneIntervalDays: 14
    repository: immich-restic
    cacheCapacity: 2Gi
    storageClassName: nfs-client
    moverSecurityContext:
      runAsUser: 0
      runAsGroup: 0
      fsGroup: 0
    retain:
      daily: 14
      weekly: 4
      within: 7d
