apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/immich-app/immich-server
      tag: v1.58.0
    command: /bin/sh
    args:
      - ./start-server.sh
    envFrom:
      - secretRef:
          name: immich
      - configMapRef:
          name: immich
    persistence:
      data:
        enabled: true
        existingClaim: immich-nfs-pvc
        mountPath: /usr/src/app/upload
    service:
      main:
        ports:
          http:
            port: 3001
