---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-server
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.8
            env:
              - name: INIT_POSTGRES_HOST
                value: ${POSTGRES_RW_URL}
              - name: INIT_POSTGRES_DBNAME
                value: immich
                # valueFrom:
                #   configMapKeyRef:
                #     name: immich
                #     key: DB_DATABASE_NAME
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: postgres-superuser
                    key: password
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: immich
                    key: DB_USERNAME
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: immich
                    key: DB_PASSWORD
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.101.0
            envFrom:
              - secretRef:
                  name: immich
              - configMapRef:
                  name: immich
            command: /bin/sh
            args:
              - ./start-server.sh
        pod:
          securityContext:
            runAsUser: ${CONTAINER_UID}
            runAsGroup: ${CONTAINER_GID}
            runAsNonRoot: true
    service:
      main:
        ports:
          http:
            port: 3001
    ingress:
      main:
        enabled: true
        annotations:
          nignx.ingress.kubernetes.io/force-ssl-redirect: 'true'
          nginx.ingress.kubernetes.io/proxy-body-size: '0'
        hosts:
          - host: &host photos.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        enabled: true
        existingClaim: immich-nfs-pvc
        globalMounts:
          - path: /usr/src/app/upload
