---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-gateway
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
        pod:
          topologySpreadConstraints:
            - maxSkew: 1
              minDomains: 2
              topologyKey: kubernetes.io/hostname
              whenUnsatisfiable: DoNotSchedule
              nodeTaintsPolicy: Honor
              matchLabelKeys:
                - pod-template-hash
              labelSelector:
                matchLabels:
                  gateway.envoyproxy.io/owning-gateway-name: envoy-gateway
                  gateway.envoyproxy.io/owning-gateway-namespace: ingress
      envoyPDB:
        minAvailable: 1
