---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: esphome
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: zigbee2mqtt
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: linkding
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: home-assistant-code
      namespace: default
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: vmagent-vm-stack
      namespace: monitoring
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: vmsingle-vm-stack
      namespace: monitoring
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: victoria-logs-victoria-logs-single-server
      namespace: monitoring
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: hubble
      namespace: kube-system
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: rook-ceph-dashboard
      namespace: rook-ceph
  oidc:
    provider:
      issuer: "https://sso.cranit.ch/application/o/gateway/"
    clientID: "8lRVJAKvaAvnGZVcrSVtFbMkmpLBQoauOi0fOuAZ"
    clientSecret:
      name: envoy-oidc-secret
    redirectURL: "https://esphome.cranit.ch/oauth2/callback"
    logoutPath: "/oauth2/logout"
    cookieDomain: "cranit.ch"
