---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: envoy-gateway
  namespace: ingress
spec:
  interval: 15m
  chartRef:
    kind: OCIRepository
    name: envoy-gateway
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  dependsOn:
    - name: cert-manager
      namespace: ingress
