---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAuth
metadata:
  name: vmauth-select-all
  namespace: monitoring
spec:
  # TODO???? 
  # ...
  # provide access to all users
  selectAllByDefault: true
  httpRoute:
      parentRefs:
        - name: envoy-gateway
          namespace: ingress
      hostnames:
        - vmauth-external.${S_HOMEPROD_DOMAIN}
  # TODO: manually verify VMAuth HTTPRoute works after migration (requires VM_GATEWAY_API_ENABLED=true on operator)
---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMUser
metadata:
  name: vmuser-proxmox
  namespace: monitoring
spec:
  tokenRef:
    name: vmuser-secret
    key: proxmox
  targetRefs:
    - crd:
        kind: VMAgent
        name: victoria-metrics-k8s-stack
        namespace: monitoring
      paths: ["/.*"]  # TODO
