---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/onedr0p/postgres-initdb:14.8
        imagePullPolicy: IfNotPresent
        env:
          - name: POSTGRES_HOST
            value: ${POSTGRES_RW_URL}
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: tandoor
                key: POSTGRESS_PORT
          - name: POSTGRES_SUPER_PASS
            valueFrom:
              secretKeyRef:
                name: postgres-superuser
                key: password
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: tandoor
                key: POSTGRESS_USER
          - name: POSTGRES_PASS
            valueFrom:
              secretKeyRef:
                name: tandoor
                key: POSTGRESS_PASSWORD
    image:
      repository: docker.io/vabene1111/recipes
      tag: 1.5.1
    env:
      TIMEZONE: ${TZ}
      ENABLE_METRICS: 1
      ENABLE_SIGNUP: 0
      POSTGRESS_PORT: 5432
    envFrom:
      - secretRef:
          name: tandoor
    persistence:
      static:
        enabled: true
        existingClaim: tandoor-static
        mountPath: /opt/recipes/static
      media:
        enabled: true
        existingClaim: tandoor-media
        mountPath: /opt/recipes/media
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
        hosts:
          - host: &host "recipes.${S_HOMEPROD_DOMAIN}"
            paths:
              - path: /
        tls:
          - hosts:
              - *host
    podSecurityContext:
      runAsUser: 1000
      runAsGroup: 100
      fsGroup: 100
      fsGroupChangePolicy: "OnRootMismatch"
