---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tandoor
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 100
        fsGroup: 100
        fsGroupChangePolicy: Always
    controllers:
      main:
        initContainers:
          01-init-db:
            imagePullPolicy: IfNotPresent
            env:
              - name: POSTGRES_HOST
                value: ${POSTGRES_RW_URL}
              - name: POSTGRES_DB
                valueFrom:
                  secretKeyRef:
                    name: tandoor
                    key: POSTGRES_DB
              - name: POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: postgres-superuser
                    key: password
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: tandoor
                    key: POSTGRES_USER
              - name: POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: tandoor
                    key: POSTGRES_PASSWORD
            image:
              repository: ghcr.io/onedr0p/postgres-initdb
              tag: '14.8'
        containers:
          main:
            image:
              repository: docker.io/vabene1111/recipes
              tag: 1.5.10
            envFrom:
              - secretRef:
                  name: tandoor
            env:
              TIMEZONE: ${TZ}
              ENABLE_METRICS: 1
              ENABLE_SIGNUP: 0
              POSTGRES_HOST: ${POSTGRES_RW_URL}
              POSTGRES_PORT: 5432
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        annotations: null
        hosts:
          - host: recipes.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - recipes.${S_HOMEPROD_DOMAIN}
        className: nginx
    persistence:
      static:
        enabled: true
        existingClaim: tandoor-static
        globalMounts:
          - path: /opt/recipes/staticfiles
      media:
        enabled: true
        existingClaim: tandoor-media
        globalMounts:
          - path: /opt/recipes/mediafiles
