---
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-media-restic
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${S_VOLSYNC_B2_REPO}-tandoor-media
  RESTIC_PASSWORD: ${S_VOLSYNC_B2_PASSWORD}
  B2_ACCOUNT_ID: ${S_VOLSYNC_B2_ID}
  B2_ACCOUNT_KEY: ${S_VOLSYNC_B2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tandoor-media-restic
  namespace: default
spec:
  sourcePVC: tandoor-media
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: tandoor-media-restic
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 111
      runAsGroup: 111
      fsGroup: 111
    retain:
      daily: 7
      within: 3d
---
apiVersion: v1
kind: Secret
metadata:
  name: tandoor-static-restic
  namespace: default
type: Opaque
stringData:
  RESTIC_REPOSITORY: ${S_VOLSYNC_B2_REPO}-tandoor-static
  RESTIC_PASSWORD: ${S_VOLSYNC_B2_PASSWORD}
  B2_ACCOUNT_ID: ${S_VOLSYNC_B2_ID}
  B2_ACCOUNT_KEY: ${S_VOLSYNC_B2_KEY}
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: tandoor-media-restic
  namespace: default
spec:
  sourcePVC: tandoor-static
  trigger:
    schedule: "0 2 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: tandoor-static-restic
    cacheCapacity: 2Gi
    volumeSnapshotClassName: csi-ceph-blockpool
    storageClassName: ceph-block
    moverSecurityContext:
      runAsUser: 111
      runAsGroup: 111
      fsGroup: 111
    retain:
      daily: 7
      within: 3d
