---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/vaultwarden/server
              tag: 1.33.1
            env:
              TZ: ${TZ}
              DOMAIN: https://passwords.${S_HOMEPROD_DOMAIN}
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden
                    key: ADMIN_TOKEN
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: default-cluster-pguser-vaultwarden
                    key: uri
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host passwords.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
