---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        initContainers:
          01-init-db:
            env:
              - name: INIT_POSTGRES_HOST
                value: ${POSTGRES_RW_URL}
              - name: INIT_POSTGRES_DB_NAME
                value: vaultwarden
              - name: INIT_POSTGRES_SUPER_PASS
                valueFrom:
                  secretKeyRef:
                    name: postgres-superuser
                    key: password
              - name: INIT_POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden
                    key: POSTGRES_USER
              - name: INIT_POSTGRES_PASS
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden
                    key: POSTGRES_PASS
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14.8
        containers:
          main:
            image:
              repository: docker.io/vaultwarden/server
              tag: 1.30.5
            env:
              TZ: ${TZ}
              DOMAIN: https://passwords.${S_HOMEPROD_DOMAIN}
              ADMIN_TOKEN:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden
                    key: ADMIN_TOKEN
              DATABASE_URL:
                valueFrom:
                  secretKeyRef:
                    name: vaultwarden
                    key: POSTGRES_URL
    service:
      main:
        ports:
          http:
            port: 80
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host passwords.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        size: 1Gi
        accessMode: ReadWriteOnce
