apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
    namespace: default
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:4hXSWyeZQg/4Hpc=,iv:W2i8OHPgKigFiavAhH+XZ1R4PVUxxAlOLOHftF/1hX4=,tag:Wscvw2K6gd2uKWKk+i80bA==,type:str]
    POSTGRES_PASS: ENC[AES256_GCM,data:jYi3ivWmsmyvh281Zy234egTFNQMWPkOsx0=,iv:dgVnUaymnn8zHXso6deSMp/gy5wFGMDOXo2UdKyj3Rc=,tag:GzTBtFaCVBzI9ja+RbVRNg==,type:str]
    POSTGRES_URL: ENC[AES256_GCM,data:VxCPECJ6K7+G55+r8x0q39/5YyksFUBLzPp0SnaI8CGNUPx5HpG2UpgQeIOK06kvYDaDNFYVovj4IBVquOXQE/lHLhiaAryy5OyeJ4c=,iv:RG/KubUna6nIen7spPcOWPEUCUfnYH4SN3CXQ9Ya0VE=,tag:OLbckTmgrFcB4vKuWQAxqQ==,type:str]
    ADMIN_TOKEN: ENC[AES256_GCM,data:TgPfhXNM6UXwQTlkVBFU2ZOy6191XaHHZywyeezJgROi708QG/lIsKpA34Q=,iv:hIzLdo0rczItxq4Jl4YD/7bShaLMnn8+p0a3JZTzITU=,tag:NxwXQG5UAOItUlrVs/D93w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ekRtR0NJMThJMWw0dVZT
            SEx0aXpZaXBRNnIxbGZodGY3Yzd3OTAxOWlrCjNabFRGcFZqOEJzV3kvOVhXKzda
            bXAvWGdTRzM2L1NXeVpkWlBTWjcvcDQKLS0tIE9kaDRkSldia3AvTU8yeG5lR2F2
            dzJaWkpZZkpPc1NYa040bms1Y0M5N3MK7Xe+VcwlOFgdnAsqrDajJ4hd1VngT/7m
            UIIa1uvgIL3U0iSXnpEzzJ4sLecGToq7GQlWrKc5YkKKnXDIL6ieIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-27T08:45:54Z"
    mac: ENC[AES256_GCM,data:acrrB6Vz/84OPxdgybkd6EEvG1Rh2TURgANTUfIpKLSFtwkpGen6a4FGMyu2SUEHYicJHDP1xTrxdX1E+SeKvN8k3CVBhTZo8JBuDjceaIbNm5zkSyVsQ3+A5ThaGtokdkhOWHnlqDiTPEzGg3xDtBXAmCzjfTtRbrQ+7ejD2V8=,iv:CAendzsoGNz6UlcF9HzbbhSGQqWmgCjd98C/LBHapIs=,tag:EW+KjW1bNQd5ula0+SiawA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
