apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: immich-web
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 1.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: immich-server
  values:
    image:
      repository: ghcr.io/immich-app/immich-web
      tag: v1.52.1
    command: /bin/sh
    args:
      - ./entrypoint.sh
    envFrom:
      - secretRef:
          name: immich
      - configMapRef:
          name: immich
    persistence:
      data:
        enabled: true
        existingClaim: immich-nfs-pvc
        mountPath: /usr/src/app/upload
    service:
      main:
        ports:
          http:
            port: 3000
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/configuration-snippet: |
            rewrite /api/(.*) /$1 break;
          nignx.ingress.kubernetes.io/force-ssl-redirect: "true"
          nginx.ingress.kubernetes.io/proxy-body-size: "0"
        hosts:
          - host: &host photos.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
              - path: /api
                pathType: Prefix
                service:
                  name: immich-server
                  port: 3001
        tls:
          - hosts:
              - *host
