# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app karakeep
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 4.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: ${CONTAINER_UID}
        runAsGroup: ${CONTAINER_GID}
        fsGroup: ${CONTAINER_FSGROUP}
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault
    controllers:
      karakeep:
        # TODO: look at adding this back if possible. currently causes a bunch of S6 errors.
        # defaultContainerOptions:
        #   securityContext:
        #     allowPrivilegeEscalation: false
        #     capabilities:
        #       drop:
        #         - ALL
        containers:
          app:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.27.1
            env:
              BROWSER_WEB_URL: http://karakeep-chrome.default.svc.cluster.local:9222
              CRAWLER_DOWNLOAD_BANNER_IMAGE: true
              CRAWLER_ENABLE_ADBLOCKER: true
              CRAWLER_STORE_SCREENSHOT: true
              CRAWLER_FULL_PAGE_SCREENSHOT: true
              DATA_DIR: /data
              MAX_ASSET_SIZE_MB: 128
              MEILI_ADDR: http://karakeep-meilisearch.default.svc.cluster.local:7700
              NEXTAUTH_URL: https://reader.${S_HOMEPROD_DOMAIN}
              DISABLE_NEW_RELEASE_CHECK: true
              DISABLE_PASSWORD_AUTH: true
              OAUTH_WELLKNOWN_URL: https://sso.${S_HOMEPROD_DOMAIN}/application/o/karakeep/.well-known/openid-configuration
              OPENAI_BASE_URL: "https://generativelanguage.googleapis.com/v1beta"
              INFERENCE_TEXT_MODEL: gemini-2.0-flash
              INFERENCE_IMAGE_MODEL: gemini-2.0-flash
            envFrom:
              - secretRef:
                  name: *app
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
      chrome:
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        containers:
          app:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124
            command:
              - chromium-browser
            args:
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --disable-background-timer-throttling
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
      meilisearch:
        defaultContainerOptions:
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
        pod:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - karakeep
                  topologyKey: kubernetes.io/hostname
        containers:
          app:
            image:
              repository: docker.io/getmeili/meilisearch
              tag: v1.22.1
            args:
              - /bin/meilisearch
              - --experimental-dumpless-upgrade
            env:
              MEILI_NO_ANALYTICS: true
              MEILI_MASTER_KEY:
                valueFrom:
                  secretKeyRef:
                    name: *app
                    key: MEILI_MASTER_KEY
    service:
      app:
        controller: *app
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    ingress:
      main:
        enabled: true
        hosts:
          - host: &host reader.${S_HOMEPROD_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
        className: nginx
    persistence:
      data:
        existingClaim: *app
        advancedMounts:
          karakeep:
            app:
              - path: /data
                subPath: karakeep
          meilisearch:
            app:
              - path: /meili_data
                subPath: meilisearch
      # This is a workaround to create cache dirs (nonroot cannot mkdir)
      cache:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /.cache
      appcache:
        type: emptyDir
        advancedMounts:
          karakeep:
            app:
              - path: /app/apps/web/.next/cache
