---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep
  namespace: default
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: ceph-block
  resources:
    requests:
      storage: 4Gi
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: karakeep-destination
