apiVersion: v1
kind: Secret
metadata:
    name: flux-webhook-token
    namespace: flux-system
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:lJ9pPGmaN30Rck4Tvypqick2svqkNlPiz2A552/b2m8anc1CLE93ww9P0c4=,iv:8imMWwoYIPvYTKcjfd+8R33O6JJ4OyLeLNfXoh/7c2I=,tag:Qq8mlIkAM+ZixViALbfR3w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2OGNqQ2xhb0xvR2pDM3hx
            VTJic0tkS04zQ3N6VE9jRWYxbGNEbnh2dW4wCmoxWFVqKy9mVEdYT05TVVk2YWlW
            RDgyUHBiR1pSaDV6dlJZKyt2c3E1ZzAKLS0tICtkNUh3aVJmZHNETHJDaFNKcmFY
            SGxWRmJKVjljN0hPNXRjbVlvK0pMRUEKtsScwUVDWTMRKG/zzRHl+TRAhlZ2vIwY
            qG/mnMagw4Cj+Ko1M1rqx4yb/7zmN3II9xy2mqknDckfQnGyaRL/vA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1fe4mnzz5uv0c0445m2f9w56r9ydx2lfp5vfx4qchlevfhsaky35sh2zgey
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-01T11:27:08Z"
    mac: ENC[AES256_GCM,data:a8fVOvaKiB20y1MepFpMuF7l5uQNKYduGB9zUcfNUmsp6AuHy/mwxdIdHsfPUk/n19UQVpgXDWmiaDBjEBVGQO4biUjlxWJBHGo8LJHMKPRJ9SvzM2ovF8wqiWoEeUisJbU3CkAnodxGmA1Cs95oOENABwrVQJGODlzdjNueIho=,iv:HnhFJgxouqhlRIG8/0LLNdaRZvUi4tNJM/IUtlAtcEw=,tag:93kblc7faaAWRUHKGCK0Bw==,type:str]
    version: 3.13.1
