---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich-microservices
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v1.102.3
            env:
              - name: DB_URL
                valueFrom:
                  secretKeyRef:
                    name: immich-cluster-pguser-immich
                    key: uri
            envFrom:
              - secretRef:
                  name: immich
              - configMapRef:
                  name: immich
            command: /bin/sh
            args:
              - ./start-microservices.sh
        pod:
          securityContext:
            runAsUser: ${CONTAINER_UID}
            runAsGroup: ${CONTAINER_GID}
            runAsNonRoot: true
    service:
      main:
        enabled: false
    persistence:
      data:
        enabled: true
        existingClaim: immich-nfs-pvc
        globalMounts:
          - path: /usr/src/app/upload
