---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: ingress
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
    prometheus.io/scheme: http
spec:
  interval: 15m
  chart:
    spec:
      chart: ingress-nginx
      version: 4.6.0
      sourceRef:
        kind: HelmRepository
        name: ingress-nginx-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: cert-manager
      namespace: ingress
  values:
    controller:
      ingressClassResource:
        default: true
      extraArgs:
        default-ssl-certificate: "ingress/homeprod-domain-tls"
      metrics:
        enabled: true
      resources:
        requests:
          cpu: 10m
          memory: 100Mi
        limits:
          memory: 500Mi
