apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: konflate-secret
  namespace: utils
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: konflate-secret
    template:
      engineVersion: v2
      data:
        KONFLATE_APP_PRIVATE_KEY: "{{ .KONFLATE_PRIVATE_KEY }}"
        KONFLATE_WEBHOOK_SECRET: "{{ .KONFLATE_WEBHOOK_SECRET }}"
        KONFLATE_APP_ID: "{{ .KONFLATE_APP_ID }}"
        KONFLATE_INSTALLATION_ID: "{{ .KONFLATE_INSTALLATION_ID }}"
  dataFrom:
    - extract:
        key: konflate
