---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.9.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  values:
    toolbox:
      enabled: false
#    monitoring:
#      enabled: false
      # createPrometheusRules: true
# TODO: https://github.com/szinn/k8s-homelab/blob/main/cluster/core/rook-ceph/cluster/helm-release.yaml#L127
#   ingress:
#     dashboard:
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
#     dashboard:
#       enabled: true
#       urlPrefix: /
#       ssl: false
      mon:
        count: 1
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "homeprod-w01"
            devices:
              - name: "scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
      resources:
        mgr:
          limits:
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        mon:
          limits:
            memory: "1Gi"
          requests:
            cpu: "1000m"
            memory: "512Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "1000m"
            memory: "1Gi"
        prepareosd:
          limits:
            memory: "400Mi"
          requests:
            cpu: "500m"
            memory: "50Mi"
        mgr-sidecar:
          limits:
            memory: "100Mi"
          requests:
            cpu: "100m"
            memory: "40Mi"
        crashcollector:
          limits:
            memory: "60Mi"
          requests:
            cpu: "100m"
            memory: "60Mi"
        logcollector:
          limits:
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "100Mi"
        cleanup:
          limits:
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "100Mi"
    cephBlockPoolVolumeSnapshotClass:
      enabled: false
