---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: {port}
    prometheus.io/scheme: http
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.18.6
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  values:
    toolbox:
      enabled: true
# TODO issue when starting up because service service monitor is missing (ceph-cluster-controller: failed to reconcile CephCluster "rook-ceph/rook-ceph". failed to reconcile cluster "rook-ceph": failed to configure local ceph cluster: failed to create cluster: failed to start ceph mgr: failed to enable mgr services: failed to enable service monitor: service monitor could not be enabled: failed to create servicemonitor. the server could not find the requested resource (post servicemonitors.monitoring.coreos.com)
    monitoring:
      enabled: false
    ingress:
      dashboard:
        ingressClassName: "nginx"
        annotations:
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.default.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://rook.${S_HOMEPROD_DOMAIN}/outpost.goauthentik.io/start?rd=$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        host: 
          name: "rook.${S_HOMEPROD_DOMAIN}"
          path: "/"
        tls:
         - hosts:
            - "rook.${S_HOMEPROD_DOMAIN}"
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      mon:
        count: 2
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "homeprod-cw01"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
          - name: "homeprod-cw02"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
          - name: "homeprod-cw03"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
      resources:
        mgr:
          limits:
            memory: "1Gi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        mon:
          limits:
            memory: "2Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "200m"
            memory: "1Gi"
        prepareosd:
          limits:
            memory: "400Mi"
          requests:
            cpu: "250m"
            memory: "20Mi"
        mgr-sidecar:
          limits:
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "25Mi"
        crashcollector:
          limits:
            memory: "60Mi"
          requests:
            cpu: "50m"
            memory: "30Mi"
        logcollector:
          limits:
            memory: "1Gi"
          requests:
            cpu: "50m"
            memory: "50Mi"
        cleanup:
          limits:
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "50Mi"
    #     requests:
    #       cpu: "100m"
    cephBlockPoolVolumeSnapshotClass:
      enabled: false
    cephFileSystems: []
    cephObjectStores: []
    cephBlockPools:
      - name: ceph-blockpool
        spec:
          failureDomain: host
          replicated:
            size: 2
        storageClass:
          enabled: true
          name: ceph-block
          allowVolumeExpansion: true
          volumeBindingMode: Immediate
          isDefault: true
          parameters:
            csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
            csi.storage.k8s.io/fstype: ext4
            csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
            csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
            csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
            imageFeatures: layering
            imageFormat: '2'
