---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.11.3
      sourceRef:
        kind: HelmRepository
        name: rook-ceph-charts
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  dependsOn:
    - name: rook-ceph-operator
      namespace: rook-ceph
  values:
    toolbox:
      enabled: true
    monitoring:
      enabled: false
      createPrometheusRules: false
    ingress:
      dashboard:
        ingressClassName: "nginx"
        host: 
          name: "rook.${S_HOMEPROD_DOMAIN}"
          path: "/"
        tls:
         - hosts:
            - "rook.${S_HOMEPROD_DOMAIN}"
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      mon:
        count: 1
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "homeprod-cw01"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
          - name: "homeprod-cw02"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
          - name: "homeprod-cw03"
            devices:
              - name: "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1"
      resources:
        mgr:
          limits:
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        mon:
          limits:
            memory: "2Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        osd:
          limits:
            memory: "4Gi"
          requests:
            cpu: "500m"
            memory: "1Gi"
        prepareosd:
          limits:
            memory: "400Mi"
          requests:
            cpu: "250m"
            memory: "20Mi"
        mgr-sidecar:
          limits:
            memory: "100Mi"
          requests:
            cpu: "50m"
            memory: "25Mi"
        crashcollector:
          limits:
            memory: "60Mi"
          requests:
            cpu: "50m"
            memory: "30Mi"
        logcollector:
          limits:
            memory: "1Gi"
          requests:
            cpu: "50m"
            memory: "50Mi"
        cleanup:
          limits:
            memory: "1Gi"
          requests:
            cpu: "250m"
            memory: "50Mi"
    cephBlockPoolVolumeSnapshotClass:
      enabled: false
    cephFileSystems: []
    cephObjectStores: []
